### ISSUE TITLE
Como posso ajudar ?

### ISSUE THREAD

**Issue by VniusLees987346** [tst-labs/esocial#108]
olá , primeiramente gostaria de saber qual a melhor maneira de contribuir com o projeto , gostei bastante da iniciativa, a priori gostaria de desenvolver a parte de integração com o seu projeto , mas estou meio perdido aqui para criar os objetos de ocorrencia por exemplo , (Preencher o objeto DTO ), voces teriam algum exemplo pronto ? é viavel criar essa parte para implementar no seu projeto ?

**Comment by VniusLees987346** [comment]
aqui no meu caso somos optantes do simples nacional , queria fazer algo simples aqui pra conectar a folha de pagamento em java a sua api

**Comment by tiagobentotst** [comment]
Boa tarde,
Agradecemos pelo seu interesse no projeto. Para fazer contribuições, basta seguir os passos no [Contributing](https://github.com/tst-labs/esocial/blob/master/CONTRIBUTING.md). Buscamos ajuda para funcionalidades que possam ser de interesse para todos que vão usar a ferramenta.

Temos vários exemplos de json, que por sua vez são transformados em objetos DTO. Os arquivos ficam na pasta [esocial/src/esocial-jt-service/src/main/resources/exemplos/](https://github.com/tst-labs/esocial/tree/master/src/esocial-jt-service/src/main/resources/exemplos) e também podem acessar pela API, com a aplicação no ar em /esocial-jt-service/ocorrencias/exemplos

Você pode enviar qualquer um desses json com o método POST (via linha de comando, Postman, etc) ou fazer um parse em sua aplicação de json para objeto java.

Consulte mais detalhes no [README.md](https://github.com/tst-labs/esocial/tree/master/src/esocial-jt-service) do projeto, mais especificamente na parte da [API](https://github.com/tst-labs/esocial/tree/master/src/esocial-jt-service#api-rest)

Caso tenha mais dúvidas, fique à vontade para continuar respondendo a esta issue.

Um abraço

**Comment by VniusLees987346** [comment]
tiago , obrigado pela resposta , até ai eu entendi , o que "ta pegando" é gerar criar o objeto java ocorrenciaDTO para transformá-lo em json, talvez você tenha algum exemplo , parece que tem que instanvciar várias classes para ter um json completo , vou postar um exemplo , veja se está correto . `OcorrenciaDTO ocorenciaDto = new OcorrenciaDTO(INFORMACOES_EMPREGADOR, INCLUSAO, "321456", new Date());
        IdePeriodo idePeriodo = new IdePeriodo();
        InfoCadastro infoCadastro = new InfoCadastro();
        infoCadastro.setContato(new Contato().setNmCtt("Ambrózio Pereira Da Silva"));
        IdePeriodo novaValidade = new IdePeriodo();
        InformacoesEmpregador informacoesEmpregador = new InformacoesEmpregador();
        informacoesEmpregador.setIdeEmpregador(new IdeEmpregador());
        InfoEmpregador infoEmpregador = new InfoEmpregador();
        infoEmpregador.setIdePeriodo(idePeriodo);
        infoEmpregador.setInfoCadastro(infoCadastro);
        infoEmpregador.setNovaValidade(novaValidade);
        ocorenciaDto.setDadosOcorrencia(informacoesEmpregador);`

seria isso mesmo (claro que completando mais alguns dados)?  

sobre a contribuição , voce tem uma lista das funcionalidades que precisa ? posso fazer algo que facilite a geração desses json por exemplo ? acha que seria interessante ?

**Comment by tiagobentotst** [comment]
A forma tradicional de se fazer isso em Java é assim mesmo. Você também pode usar reflexão, outras bibliotecas, como o [Mapstruct](http://mapstruct.org/) ou criar _Factorys_ para isso. Pode até mesmo nem utilizar os objetos DTO e gerar o json de uma outra forma.

Observe que a nossa API recebe objetos json. Logo, a forma que você irá gerar esses objetos são totalmente indiferentes para a nossa aplicação. Pode-se utilizar Java (com qualquer framework a sua escolha), Node.js, C++, etc. Nós, por exemplo, já usamos ferramenta de [ETL](https://github.com/tst-labs/esocial/tree/master/exemplos/pentaho) para gerar json diretamente na transformação.

Não se prenda à utilização dos objetos DTO, pois eles são apenas uma referência. Quaisquer ideias que tiver com novas implementações serão muito bem vindas!

**Comment by VniusLees987346** [comment]
essa ferramenta de etl que não tenho conhecimento ... vou estudar sobre ela , deve ser a forma mais facil , obrigado pela dica

**Comment by VniusLees987346** [comment]
eu to fazendo um post com esse json abaixo , 

{
	"tipoOcorrencia": "INFORMACOES_EMPREGADOR",
	"referencia": "00509968000148",
	"operacao": "INCLUSAO",
	"dataOcorrencia": 1541516962884,
	"dadosOcorrencia": {
		"tipo": ".InformacoesEmpregador",
		"ideEmpregador": {
			"tpInsc": 1,
			"nrInsc": "00509968000148"
		},
		"infoEmpregador": {
			"idePeriodo": {
				"iniValid": "2018-11",
				"fimValid": null
			},
			"novaValidade": null,
			"infoCadastro": {
				"nmRazao": "LUIZ GONZAGA DOS REIS AGUIAR ME",
				"classTrib": "85",
				"natJurid": "1074",
				"indCoop": 0,
				"indConstr": 0,
				"indDesFolha": 0,
				"indOptRegEletron": 1,
				"indEntEd": "N",
				"indEtt": "N",
				"nrRegEtt": null,
				"dadosIsencao": null,
				"contato": {
					"nmCtt": "LUIZ GONZAGA DOS REIS AGUIAR",
					"cpfCtt": "21105529649",
					"foneFixo": "3432365550",
					"foneCel": "34996717792",
					"email": "mariacustodia@aps.inf.br"
				},
				"infoOP": {
					"nrSiafi": "080001",
					"infoEFR": null,
					"infoEnte": null
				},
				"infoOrgInternacional": null,
				"softwareHouse": [
					{
						"cnpjSoftHouse": "42934687000182",
						"nmRazao": "APS SOFTWARE LTDA",
						"nmCont": "AMBROZIO PEREIRA DA SILVA",
						"telefone": "34323365550",
						"email": "ambrozio@aps.inf.br"
					}
				],
				"infoComplementares": {
					"situacaoPJ": {
						"indSitPJ": 0
					}
				}
			}
		}
	}
}

o processamento visualizado pelo cockpit fica apenas no em fila , parece que deu algum erro , 
o json que ele me retornou foi . 

{
   "id": 23,
   "tipoOcorrencia": "INFORMACOES_EMPREGADOR",
   "referencia": "00509968000148",
   "operacao": "INCLUSAO",
   "dataOcorrencia": 1541516962884,
   "dataRecebimento": 1541517235650,
   "dadosOcorrencia":    {
      "tipo": ".InformacoesEmpregador",
      "ideEmpregador":       {
         "tpInsc": 1,
         "nrInsc": "00509968000148"
      },
      "infoEmpregador":       {
         "idePeriodo":          {
            "iniValid": "2018-11",
            "fimValid": null
         },
         "novaValidade": null,
         "infoCadastro":          {
            "nmRazao": "LUIZ GONZAGA DOS REIS AGUIAR ME",
            "classTrib": "85",
            "natJurid": "1074",
            "indCoop": 0,
            "indConstr": 0,
            "indDesFolha": 0,
            "indOptRegEletron": 1,
            "indEntEd": "N",
            "indEtt": "N",
            "nrRegEtt": null,
            "dadosIsencao": null,
            "contato":             {
               "nmCtt": "LUIZ GONZAGA DOS REIS AGUIAR",
               "cpfCtt": "21105529649",
               "foneFixo": "3432365550",
               "foneCel": "34996717792",
               "email": "mariacustodia@aps.inf.br"
            },
            "infoOP":             {
               "nrSiafi": "080001",
               "infoEFR": null,
               "infoEnte": null
            },
            "infoOrgInternacional": null,
            "softwareHouse": [            {
               "cnpjSoftHouse": "42934687000182",
               "nmRazao": "APS SOFTWARE LTDA",
               "nmCont": "AMBROZIO PEREIRA DA SILVA",
               "telefone": "34323365550",
               "email": "ambrozio@aps.inf.br"
            }],
            "infoComplementares":             {
               "situacaoPJ": {"indSitPJ": 0},
               "situacaoPF": null
            }
         }
      }
   },
   "evento": null
}

sabe onde eu to errando ? eu acho que pode ser os parametro que estou passando errado ....

**Comment by tiagobentotst** [comment]
Apareceu algum erro no console da aplicação?

Com o [json de exemplo](https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-service/src/main/resources/exemplos/informacoes_empregador.json) (alterando o CNPJ) funciona?

**Comment by VniusLees987346** [comment]
esqueci o principal no json , de alterar o cnpj rssrsrsrs , Obrigado !
