### ISSUE TITLE
Erro na fase de testes ao gerar o build da Aplicação - RetornoProcessamentoTest.deveCriarObjetoQuandoHaErroDeProcessamento

### ISSUE THREAD

**Issue by thiagoacioly** [tst-labs/esocial#110]
após executar o comando mvn clean package está gerando o seguinte erro na fase de testes. 

O ambiente windows 7, com java 8 e maven 3.5.4.

[INFO] Running br.jus.tst.esocialjt.comunicacaogov.RetornoProcessamentoTest
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.309 s <<< FAILURE! - in br.jus.tst.esocialjt.comunicacaogov.RetornoProcessamentoTest
[ERROR] deveCriarObjetoQuandoHaErroDeProcessamento(br.jus.tst.esocialjt.comunicacaogov.RetornoProcessamentoTest)  Time elapsed: 0.343 s  <<< ERROR!
java.lang.NullPointerException
        at br.jus.tst.esocialjt.comunicacaogov.RetornoProcessamentoTest.deveCriarObjetoQuandoHaErroDeProcessamento(RetornoProcessamentoTest.java:31)

-----------------------

[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   RetornoProcessamentoTest.deveCriarObjetoQuandoHaErroDeProcessamento:31 » NullPointer
[INFO]
[ERROR] Tests run: 331, Failures: 0, Errors: 1, Skipped: 0

-------------------------------
com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Byte invÃ¡lido 2 da sequÃªncia UTF-8 do byte 3. at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(Unknown Source) at com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(Unknown Source) at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(Unknown Source) at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.skipChar(Unknown Source) at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source) at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source) at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source) at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source) at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source) at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source) at javax.xml.parsers.DocumentBuilder.parse(Unknown Source) at br.jus.tst.esocialjt.comunicacaogov.RetornoProcessamentoUtil.obterElementosDeEventosTotalizadores(RetornoProcessamentoUtil.java:54) at br.jus.tst.esocialjt.comunicacaogov.RetornoProcessamento.buscaEventosTotalizadores(RetornoProcessamento.java:130) at br.jus.tst.esocialjt.comunicacaogov.RetornoProcessamento.criarRetornoLote(RetornoProcessamento.java:81) at br.jus.tst.esocialjt.comunicacaogov.RetornoProcessamento.setXmlRetorno(RetornoProcessamento.java:157) at br.jus.tst.esocialjt.comunicacaogov.RetornoProcessamento.<init>(RetornoProcessamento.java:27) at br.jus.tst.esocialjt.comunicacaogov.RetornoProcessamentoTest.deveCriarObjetoQuandoHaErroDeProcessamento(RetornoProcessamentoTest.java:31) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) at org.junit.runners.ParentRunner.run(ParentRunner.java:363) at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365) at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273) at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238) at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159) at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383) at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344) at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125) at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)

**Comment by thiagoacioly** [comment]
O problema está relacionado com o encoding. Durante a leitura do xml é esperado o enconding UTF-8

Encontrei duas formas para resolver o problema:
1 - Alterando o código do método RetornoProcessamentoUtil.obterElementosDeEventosTotalizadores
2 - Setando o enconding no parâmetro da JVM  -Dfile.encoding=UTF8

**Comment by thiagoacioly** [comment]
Solução 2: no ambiente windows criei uma variável de ambiente JAVA_TOOL_OPTIONS passando como valor -Dfile.encoding=UTF8
segue um link de onde tirei essa solução:
https://stackoverflow.com/questions/3017695/how-to-configure-encoding-in-maven

**Comment by thiagoacioly** [comment]
Solução1: Alterando o código do método RetornoProcessamentoUtil.obterElementosDeEventosTotalizadores. Dessa forma, não houve necessidade de realizar configurações na JVM. 

public List<Element> obterElementosDeEventosTotalizadores(String xmlRetorno) {

		List<Element> elementos = new ArrayList<>();

		DocumentBuilderFactory dbFactory = DocumentBuilderFactory.newInstance();
		try {
			//DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
			//InputStream is = new ByteArrayInputStream(xmlRetorno.getBytes());
			//Document doc = dBuilder.parse(is);
			
			//novo
			DocumentBuilder docBuilder = dbFactory.newDocumentBuilder(); 
			Document doc = docBuilder.parse(new InputSource(new StringReader(xmlRetorno))); 
			
			NodeList nodeList = doc.getElementsByTagName("tot");
			for (int i = 0; i < nodeList.getLength(); i++) {
				Node node = nodeList.item(i);
				if (node.getNodeType() == Node.ELEMENT_NODE) {
					elementos.add((Element) node);
				}
			}
			
		} catch (SAXException | IOException | ParserConfigurationException e) { 
			LOGGER.error(e.getCause().getMessage(), e);
		}
		
		
		return elementos;
	}

**Comment by tiagobentotst** [comment]
Consideramos a solução 1 mais correta. Caso já tenha feita a alteração no seu ambiente, poderia solicitar um pull request?
