### ISSUE TITLE
problema com envio do xml para envio de informações do empregador. 

### ISSUE THREAD

**Issue by WineLemes** [tst-labs/esocial#114]
olá,tudo tranquilo ?? 

estou com um erro na hora que gera o xml para envio , descobri que tem a ver com o cnpj, ao ler a documentação informa que o cnpj deve ser passado no caso de optantes pelo simples , que é meu caso , apenas os oito primeiros digitos , e isso acaba gerando um erro na estrutura do xml , o que preciso saber é ... no caso de optante pelo simples nacional , como devo passar o meu cnpj , poderiam me explicar ? agradeço a atenção desde já , até logo .

**Comment by tiagobentotst** [comment]
Olá, 

como o nosso desenvolvimento foi voltado para órgãos públicos (que usa o CNPJ completo) não chegamos a testar esse caso. Se você alterar o `application.properties` com o seu CNPJ usando 8 dígitos, o sistema consegue gerar o xml e enviar? Ou aparece algum erro?

**Comment by WineLemes** [comment]
opa , vou testar isso , tinha feito umas alterações no código , mas não alterei no properties , vou testar amanha e retorno, obrigado pela dica ! bom , essa seria uma funcionalidade que posso desenvolver para incrementar no projeto ?

**Comment by tiagobentotst** [comment]
Sem dúvidas. Caso a aplicação apresente algum erro ao alterar o arquivo de propriedades, seria muito bom que contribuísse com sua solução.

**Comment by rataodobanhado** [comment]
Estou com problema semelhante WineLemes e tiagonestotst... o meu arquivo de Informações do Empregador fica na fila de envio, tentando repetidamente, e no retorno indica apenas que deu erro, sem uma descrição do que é. Estou indicando que o CNPJ aqui tem apenas 8 dígitos no arquivo json... se for o cado de alterar o application.properties o que devo colocar lá? No application.properties aqui não tem nenhuma indicação de CNPJ, apenas o path do certificado e a senha... Desde já agradeço qualquer dica.

**Comment by tiagobentotst** [comment]
Você pode usar qualquer propriedade que está indicada no arquivo de [application.properties](https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-service/src/main/resources/application.properties) da pasta `src/esocial-jt-service/src/main/resources`.

No caso do CNPJ, o que deve ser alterado é:
`esocialjt.cnpj-empregador=00509968000148`

Não precisa alterar o arquivo que está dentro do projeto. Colocando essa propriedade no mesmo arquivo em que você indica o path do certificado, ela terá prioridade em momento de execução.

As demais propriedades (até o momento) são:

```
#Web
server.servlet.contextPath=/esocial-jt-service

#preencha caso o certificado do transmisssor seja diferente do empregador a ser cadastrado no evento S1000. Ou seja, será usado um certificado de uma Pessoa Física para envio dos eventos.
#esocialjt.tpInscIdeTransmissor=2
#esocialjt.nrInscIdeTransmissor= cpf do transmisssor

#eSocial-JT
esocialjt.cnpj-empregador=00509968000148
esocialjt.ambiente=PRODUCAO_RESTRITA
esocialjt.erros-recuperaveis=72
esocialjt.arquivoCertificado=
esocialjt.senhaCertificado=
esocialjt.arquivoCacerts=
esocialjt.senhaCacerts=changeit
esocialjt.periodoAutoMilis=10000
esocialjt.versao-esquemas-esocial="2.4.02"
esocialjt.limite-eventos-por-lote=50

#Database
spring.datasource.url=jdbc:postgresql://localhost/postgres
spring.datasource.username=postgres
spring.datasource.password=esocial
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.open-in-view=false

#Management
management.endpoints.web.exposure.include=info, health, esocial-health
management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=*
```
