### ISSUE TITLE
Atualização para versão 2.5 do eSocial.

### ISSUE THREAD

**Issue by rcvieira** [tst-labs/esocial#117]
ESOCIAL-194 (JIRA_TST)
Atualização para adequar o eSocial-JT para a versão 2.5 de acordo com a Resolução nº 19, de 9 de novembro de 2018.

Liberação prevista no eSocial(Gov) em:
Ambiente de Produção Restrita (testes): 17/12/2018
Ambiente de Produção: 21/01/2019

**Comment by tiagobentotst** [comment]
Atualizado para versão 2.5 dos eventos e 1.5 do pacote de comunicação
