### ISSUE TITLE
Dúvida - Lote

### ISSUE THREAD

**Issue by lucasbhti** [tst-labs/esocial#123]
Prezados, bom dia.

As ocorrências enviadas para o eSocial-JT são sempre enviadas ao eSocial-Gov em lotes separados?
A montagem dos lotes de envio é configurável ou os lotes sempre são compostos de uma única ocorrência?

Obrigado!

**Comment by tiagobentotst** [comment]
Boa tarde,

os lotes são montados com até 50 eventos. Mas, conforme as ocorrências vão chegando, já vão sendo enviadas para o eSocial-Gov. Por exemplo, se chegarem 10 ocorrências para o eSocial-JT, essas 10 já são enviadas para o Gov. Se nesse meio tempo chegarem mais 100, elas são enviadas de 50 em 50 para o Gov. 

Em alguns momentos a aplicação pode enviar lotes menores, mesmo que tenham vários eventos na fila. Isso acontece por causa da precedência de eventos. Por exemplo, o evento S1000 é enviado antes de todos os outros, pois somente quando ele é processado com sucesso os demais eventos são aceitos.

É possível configurar a quantidade de eventos por lote pela propriedade `esocialjt.limite-eventos-por-lote` no arquivo `application.properties`. Apenas observe que, pela regra de negócio do eSocial-Gov, eles aceitam lotes com até 50 eventos de cada vez.

**Comment by lucasbhti** [comment]
Muito obrigado.
Só mais uma pergunta.

Pelo que entendi, as ocorrências são enviadas para o eSocial-JT contendo os dados de apenas um evento, correto?
Sendo assim, como funciona a montagem dos lotes? De tempo em tempo os lotes são gerados com as ocorrências recebidas e enviados?

**Comment by tiagobentotst** [comment]
Sim, as ocorrências são enviadas uma por vez para o eSocial-JT. Pode ser que mudemos isso no futuro, se houver problema de desempenho.

Os lotes são gerados de tempos em tempos como você disse. Também existe um parâmetro para isso, chamado `esocialjt.periodoAutoMilis`. Por exemplo, se esse período for marcado como 10000 (10.000 milissegundos ou 10 segundos), a cada 10 segundos a aplicação verifica quais eventos estão na fila, gera o lote e envia. Na verdade outras tarefas são executadas durante esse ciclo, como consultar se os lotes enviados anteriormente já foram processados pelo eSocial-Gov e gravar o respectivo sucesso ou erro.

**Comment by lucasbhti** [comment]
Muito obrigado pelas informações!

**Comment by Kennedi1313** [comment]
@lucasbhti vc conseguiu colocar várias ocorrências do evento s-1010 (tabela de rubricas) no mesmo lote? Aqui enviei 10 ocorrências desse evento s-1010 e mesmo aparecendo nos logs "gerando eventos para 10 ocorrências", apenas 1 ocorrência entrava na fila por vez, e consequentemente apenas 1 ocorrência entrava no lote...
