### ISSUE TITLE
Processo fica "EM FILA"

### ISSUE THREAD

**Issue by ezequielweingartner** [tst-labs/esocial#124]
Ao enviar o TVS_INICIO 

O processo fica "EM FILA"  e não sai do status. O erro no log é:

: << "nvelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><ConsultarLoteEventosResponse xmlns="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/consulta/retornoProcessamento/v1_1_0"><ConsultarLoteEventosResult><eSocial xmlns="http://www.esocial.gov.br/schema/lote/eventos/envio/retornoProcessamento/v1_3_0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><retornoProcessamentoLoteEventos><status><cdResposta>501</cdResposta><descResposta>Solicita[0xc3][0xa7][0xc3][0xa3]o de consulta incorreta - Erro preenchimento.</descResposta><ocorrencias><ocorrencia><codigo>748</codigo><descricao>O protocolo informado [0xc3][0xa9] inv[0xc3][0xa1]lido.</descricao><tipo>1</tipo></ocorrencia></ocorrencias></status></retornoProcessamentoLoteEventos></eSocial></ConsultarLoteEventosResult></ConsultarLoteEventosResponse></s:Body></s:Envelope>"

**Comment by tiagobentotst** [comment]
Os eventos de tabela são enviados normalmente?

**Comment by tiagobentotst** [comment]
Esse erro acontecia porque o eSocial-Gov alterou o pacote de comunicação de 1.4 para 1.5. A nova versão já foi disponibilizada no eSocial-JT
