### ISSUE TITLE
Criar arquivo (json) exclusão de exclusão para evento de tabela.

### ISSUE THREAD

**Issue by marcelo225** [tst-labs/esocial#125]
Atualmente, na pasta [de exemplos](https://github.com/tst-labs/esocial/tree/master/src/esocial-jt-service/src/main/resources/exemplos) só existe a exclusão para evento [3000](https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-service/src/main/resources/exemplos/exclusao.json).
Adicionem, por gentileza, um exemplo de como enviar um **outro json de exclusão** de tabela (por exemplo, evento 1010 - Rubricas).

**Comment by tiagobentotst** [comment]
Resolvido em #126
