### ISSUE TITLE
Erro no envio do evento s1010 - Tabela Rubricas

### ISSUE THREAD

**Issue by marcelo225** [tst-labs/esocial#127]
No envio do evento s1010, o campo **Tipo** está apresentando um erro, conforme imagem anexa.
![tela](https://user-images.githubusercontent.com/4791314/52503634-4a848680-2bcd-11e9-83d7-bd6348c33b45.png)

**Comment by tiagobentotst** [comment]
O evento está correto. Somente o componente da interface (cocopit) não foi implementado para exibir as informações de Rubrica ainda.

Para que o evento seja enviado, ou seja, saia do estado "Em fila", é preciso enviar antes um evento do tipo S1000 com sucesso.

**Comment by marcelo225** [comment]
@tiagobentotst, não entendi. O evento s1000 foi o primeiro evento que foi enviado antes do evento s1010 e outros. Por exemplo, os eventos como s1005, s1020, s1035, s1040, s1070 deram certinho.

**Comment by tiagobentotst** [comment]
Bom...

é importante entender que o eSocial-JT é uma aplicação que funciona por si só no backend. Ela tem interfaces [RESTful](https://github.com/tst-labs/esocial#api-rest) para receber dados no formato Json e da mesma forma expõe os dados e estados internos da aplicação também em Json. 

O cockpit é apenas uma formatação dos dados para mostrar de uma forma mais amigável o Json exposto pelo eSocial-JT. Nós o criamos para algumas apresentações e demonstrações para as áreas de negócio. Ou seja, o cockpit é apenas uma forma de visualizar os dados expostos pelo eSocial-JT e não é essencial, podendo inclusive ser descartado ou substituído por qualquer interface gráfica que formate um arquivo Json. 

Na verdade o cockpit não é parte da solução, e foi disponibilizado somente como ponto de partida para que os desenvolvedores pudessem criar interfaces que atendam as necessidades específicas de cada empresa/órgão.

Esse erro apresentado ocorre somente na interface gráfica (cockpit). Isso quer dizer que o componente de renderização (em React.js) para o evento de rubrica (1010) ainda não foi implementado, ou seja, ele não sabe gerar o HTML a partir desse tipo de Json. No entanto, aparentemente o backend (eSocial-JT) conseguiu recebê-lo sem problemas.

Assim, peço que vejam no log da aplicação do eSocial-JT se ele apresenta alguma mensagem de erro. Também pode-se usar diretamente a [api rest](https://github.com/tst-labs/esocial#api-rest) para verificar o Json que é retornado para esse evento específico.
