### ISSUE TITLE
Erro do axis2 - No space left on device

### ISSUE THREAD

**Issue by marcelo225** [tst-labs/esocial#128]
@thiagoacioly, descobrimos um bug na aplicação o que faz com que o container "cuspa" o erro no log abaixo. 

> 2019-02-07 15:14:14.729 WARN 1 --- [io-8080-exec-60] **org.apache.axis2.deployment.util.Utils : Exception extracting jars into temporary directory : java.io.IOException: No space left on device : switching to alternate class loading mechanism**
> 2019-02-07 15:14:14.913 WARN 1 --- [io-8080-exec-34] o.s.b.a.system.DiskSpaceHealthIndicator : Free disk space below threshold. Available: 20480 bytes (threshold: 10485760 bytes)
> 2019-02-07 15:14:14.922 WARN 1 --- [io-8080-exec-57] o.s.b.a.system.DiskSpaceHealthIndicator : Free disk space below threshold. Available: 20480 bytes (threshold: 10485760 bytes)
> 2019-02-07 15:14:15.141 INFO 1 --- [io-8080-exec-60] o.a.axis2.deployment.ModuleDeployer : Deploying module: addressing-1.6.2 - **file:/tmp/esocial-jt-service-0.0.1-SNAPSHOT.jar-spring-boot-libs-ee34ce00-4c80-4fc0-ace7-b3b44a0cde40/axis2-1.6.2.jar**
> class br.jus.esocialjt.comunicacao.lote.eventos.retorno.processamento.ESocial

Dentro desta pasta file:/tmp/ do nosso container, existem vários arquivos gerados relacionados a esse axis2-1.6.2.jar. 

Sabemos que o problema seja de espaço em disco, correto?
Mas já aumentamos o espaço em disco e o problema ainda persiste. Isso porque a aplicação não limpar nesta pasta /tmp os deploys relacionados ao **axis2-1.6.2.jar**.

O problema resolve depois que fazemos outro deploy aqui, mas todas as vezes é necessário fazer deploy constantemente para limpar a pasta tmp/ do servidor.

Por que a aplicação cria um monte de jars do axis?

Vocês tireram problemas como esse? O que poderia ser feito para resolver esse problema?
Obrigado!!

**Comment by tiagobentotst** [comment]
Boa tarde,

Esse é um problema dessa biblioteca axis2. Nós já tínhamos observado este comportamento, mas ainda não tinha chegado a esse ponto de ter problemas de espaço em disco.

Nós colocamos uma atividade para estudar esse caso no futuro, mas como priorizamos outras funcionalidades, não sabemos ainda quando iremos atacar este problema específico.

Caso consigam uma solução antes da gente, peço que subam um "merge request" para que possamos integrar ao código principal

**Comment by marcelo225** [comment]
@thiagoacioly a versão atual compilada pelo maven é a 1.6.2.jar.
Porém, na versão **1.7.8** que corrige este problema.
Apesar de no pom.xml do ejt-service não referenciar o version na tag de "dependency", será necessário adicionar a tag "version"

Segue o link abaixo da issue sobre esse problema, para maiores detalhes.
https://issues.apache.org/jira/browse/AXIS2-3919

**Comment by tiagobentotst** [comment]
Excelente,

quando fizerem a alteração no pom, podem abrir um `pull request` que nós iremos verificar.
Se tiver alguma dúvida, pode consultar o nosso guia de [contributing](https://github.com/tst-labs/esocial/blob/master/CONTRIBUTING.md).
