### ISSUE TITLE
evento S1030 - Erro de processamento (105)

### ISSUE THREAD

**Issue by marcelo225** [tst-labs/esocial#129]
Olá, @thiagoacioly 

Estamos com uma dúvida de procedimento. 

Durante nossos testes ao incluir e depois excluir um determinado registro no evento S1030, não conseguimos incluir novamente o registro.

O sistema informa o seguinte erro:
"Erro de processamento (105)
O evento a ser excluído/retificado (alterado) não foi localizado na base de dados do eSocial. Ação Sugerida:Verificar se o número do recibo informado no evento, corresponde ao mesmo número de recibo do evento original. Preencher com o número do recibo do arquivo a ser retificado".

Como devemos proceder?

Obrigado.

**Comment by tiagobentotst** [comment]
Isso é realmente um bug do eSocial-JT

No nosso sistema há uma funcionalidade que, ao receber um evento de tabela como _inclusão_ de um evento que já foi incluído anteriormente, ele converte para _alteração_. Mas não foi previsto o caso de haver uma _exclusão_ após a primeira _inclusão_, assim ocorre a conversão para _alteração_ da segunda _inclusão_, ocasionando o erro.

Nós estamos avaliando qual a melhor forma de tratar esse caso. Duas opções são retirar totalmente as conversões automáticas e deixar que os sistemas de origem decidam o tipo de evento a ser enviado ou adicionar outros controles para tornar mais "inteligente" o eSocial-JT.
