### ISSUE TITLE
Erro de sequence no postgreSQL

### ISSUE THREAD

**Issue by marcelo225** [tst-labs/esocial#131]
@thiagoacioly, tudo bem?

Deparamos com esse erro abaixo:

> Caused by: org.postgresql.util.PSQLException: ERROR: nextval: reached maximum **value of sequence"seq_resposta_id" (800)** 
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433) ~[postgresql-42.2.2.jar!/:42.2.2]
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(Quer

Acredito que a causa do problema é o tamanho do sequence da resposta.
O id máximo que foi gerado é 68469 até o momento nos testes que estamos realizando com carga de dados.
Obrigado!

**Comment by tiagobentotst** [comment]
Verifique se aumentando o valor máximo da sequence no banco de dados continua apresentando o mesmo erro, por favor.
