### ISSUE TITLE
Duvida sobre contribuição

### ISSUE THREAD

**Issue by adrsant** [tst-labs/esocial#139]
Boa tarde, 
Gostaria de saber como posso contribuir com o projeto e se possível, podemos marcar uma call para conversarmos melhor?

fico no aguardo.

**Comment by tiagobentotst** [comment]
Olá, boa tarde

agradecemos pela disposição e ficamos felizes em aceitar suas contribuições. Teria algum email para entrarmos em contato?

**Comment by adrsant** [comment]
adrsant.silva@gmail.com

**Comment by tiagobentotst** [comment]
Ok, anotei seu email e apaguei a mensagem para evitar SPAM
