### ISSUE TITLE
Evento S2230 - Exemplo de arquivo de retificação para alteração contratual

### ISSUE THREAD

**Issue by marcelo225** [tst-labs/esocial#141]
@thiagoacioly, tudo bem?
Nos [exemplos] (https://github.com/tst-labs/esocial/tree/master/src/esocial-jt-service/src/main/resources/exemplos) não consta um exemplo de retificação de uma retificação. Ou, se tiver, qual é o arquivo json que faz isso?

Seria a mesma ideia desta [issue](https://github.com/tst-labs/esocial/issues/140) ?

Obrigado!!!

**Comment by tiagobentotst** [comment]
Segue o mesmo princípio de uma retificação, passando o número do recibo do evento de retificação anterior.

**Comment by marcelo225** [comment]
Ok, @thiagoacioly. Obrigado.
