### ISSUE TITLE
Tratar resposta de processamento "202 - Lote Processado com Advertências"

### ISSUE THREAD

**Issue by hednilson** [tst-labs/esocial#142]
Respostas de processamento com advertências, código 202, estão sendo mapeadas para o estado PROCESSADO_COM_ERRO. Isso foi proposital? Será que não seria mais adequado mapear para o estado PROCESSADO_COM_SUCESSO ou até mesmo um novo estado?

Atenciosamente.
Hednilson.

**Comment by lldias** [comment]
Boa tarde Hednilson,

Sim, você tem razão: resultados do tipo SUCESSO COM ADVERTÊNCIAS estão
sendo mapeados para PROCESSAMENTO COM ERRO. Acredito que não exista
motivação para isso, pois é normal um evento ser aceito com alertas - veja
https://www.youtube.com/watch?v=I9idgqB2mpk.

Talvez o ideal seja criar um novo estado para distinguir e exibir
corretamente esses alertas.

Um abraço,
Luciano.

**Comment by tiagobentotst** [comment]
Vamos colocar esta issue no backlog para futura implementação
