### ISSUE TITLE
Data-início-validade e Data-fim-validade nas Tabelas

### ISSUE THREAD

**Issue by marcelo225** [tst-labs/esocial#143]
Boa tarde, @thiagoacioly.

No item **12.3. Data-início-validade e Data-fim-validade nas Tabelas** do manual do e-social, existe a seguinte explicação quanto aos grupos de informações:

> Neste sentido, todos os eventos de tabela possuem 4 grupos de informações:
> a) **Inclusão**: utilizada para inserir novo item na tabela ou modificar um atributo de um item já existente, com uma nova vigência;
> b) **Alteração**: utilizada para alterar os atributos de um item que estavam incorretos para um determinado período que se quer alterar;
> c) **Nova validade**: utilizada para modificar a validade de uma ocorrência da tabela e, inclusive, para informar data fim de validade de uma ocorrência;
> d) **Exclusão**: utilizada para excluir uma determinada ocorrência de uma tabela. 

O grupo INCLUSAO, ALTERACAO e EXCLUSAO são tratadas conforme a descrição do manual?

Tem algum exemplo de json (evento S-1040, por exemplo), para os outros grupos que não seja INCLUSAO?

E como seria um json (evento S-1040, por exemplo) no EJT para RETIFICAÇÃO?

**Comment by tiagobentotst** [comment]
> O grupo INCLUSAO, ALTERACAO e EXCLUSAO são tratadas conforme a descrição do manual?

Sim

> Tem algum exemplo de json (evento S-1040, por exemplo), para os outros grupos que não seja INCLUSAO?

https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-service/src/main/resources/exemplos/tabela_cargo_alteracao.json

https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-service/src/main/resources/exemplos/tabela_cargo_exclusao.json

> E como seria um json (evento S-1040, por exemplo) no EJT para RETIFICAÇÃO?

Os eventos de tabela não são retificados

**Comment by marcelo225** [comment]
Ok, @thiagoacioly. Obrigado.
