### ISSUE TITLE
Dúvida de um fluxo de inclusão, exclusão e inclusão novamente

### ISSUE THREAD

**Issue by marcelo225** [tst-labs/esocial#144]
@thiagoacioly, boa tarde!

Tenho uma dúvida:
Supondo que eu faça nesta sequência: INCLUSAO -> EXCLUSAO -> INCLUSAO novamente, usando os jsons abaixo (mesmo número de referência e ideFuncao), do evento S1040, por exemplo:
```
1) Primeira inclusão:

{
	"referencia": "1",
	"tipoOcorrencia": "TABELA_FUNCAO",
	"operacao": "INCLUSAO",
	"dadosOcorrencia": {
		"tipo": ".TabelaFuncao",
		"ideEmpregador": {
			"tpInsc": 1,
			"nrInsc": "CNPJ_X" (ocultei o dado por aqui)
		},
		"infoFuncao": {
			"ideFuncao": {
				"codFuncao": "995",
				"iniValid": "2018-08"
			},
			"dadosFuncao": {
				"dscFuncao": "OFICIAL DE GABINETE DO JUIZ - FC05",
				"codCBO": "410105"
			}
		}
	},
	"dataOcorrencia": 1556907432621
}
```
2) Exclusão do registro inserido:

```
{
	"referencia": "1",
	"tipoOcorrencia": "TABELA_FUNCAO",
	"operacao": "EXCLUSAO",
	"dadosOcorrencia": {
		"tipo": ".TabelaFuncao",
		"ideEmpregador": {
			"tpInsc": 1,
			"nrInsc": "CNPJ_X" (ocultei o dado por aqui)
		},
		"infoFuncao": {
			"ideFuncao": {
				"codFuncao": "995",
				"iniValid": "2018-08"
			}
		}
	},
	"dataOcorrencia": 1556907432621
}
```

Quando eu vou incluir **novamente** o mesmo payload (json) de inclusão, dá o seguinte aviso pelo e-Social:

> O evento a ser **excluído/retificado** (alterado) não foi localizado na base de dados do eSocial. Ação Sugerida:Verificar se o número do recibo informado no evento, corresponde ao mesmo número de recibo do evento original. **Preencher com o número do recibo do arquivo a ser retificado**.

Pela mensagem acima, eu não quero retificar e muito menos alterar. Eu quero incluir novamente. Por se tratar do evento S-1040, no manual do e-Social, no item **13. Retificações e Alterações**, fala que **RETIFICAÇÃO é somente para os eventos que não seja de tabela (S-1005 a S-1080)**.

Eu sei que a chave do registro no e-social é representado pelo campo **ideFuncao (codFuncao + iniValid + fimValid)**. Por que eu não consigo inserir o mesmo dado (mesma chave) e mesma referência novamente sabendo que o mesmo já tinha sido excluído no EJT?

Obrigado!!

**Comment by tiagobentotst** [comment]
É o mesmo erro da issue #129 
Ainda não foi corrigido...

Uma pergunta... esse caso de inclusão-exclusão-inclusão é comum no ambiente de vocês ou só estão fazendo testes?

**Comment by marcelo225** [comment]
Sim, @thiagoacioly. Pode acontecer casos assim, como neste evento. Mas deveria funcionar para todos os eventos de tabela, assim como consta no item 12.3 e 13 do manual e-social. Ok?

**Comment by Claison** [comment]
estou mandando em produção os eventos 1005 como inclusão, mas o que chega para o e-social é alteração e me retorna erro.

**Comment by Claison** [comment]
"O evento a ser excluído/retificado (alterado) não foi localizado na base de dados do eSocial.\nAção Sugerida: Verificar se o número do recibo informado no evento, corresponde ao mesmo número de recibo do evento original. Preencher com o número do recibo do arquivo a ser retificado",

**Comment by rcvieira** [comment]
@tiagobentotst , fiz o merge da alteração. Você fecha a issue?
