### ISSUE TITLE
Exemplo de evento de desligamento - S2299 e S2399

### ISSUE THREAD

**Issue by marcelo225** [tst-labs/esocial#148]
@thiagoacioly, blz?
Duas dúvidas...
O [arquivo json] (https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-service/src/main/resources/exemplos/desligamento.json) de envio para o Esocial JT serve tanto para o evento S2299 como S2399 ?
Se não for, tem como adicionar um arquivo para diferenciar esses dois eventos?

Outra dúvida é sobre a retificação destes eventos por existir a opção de envio NORMAL. Estes eventos tem opção de RETIFICAÇAO. Se tiver, teria como adicionar os dois arquivos .json de envio no repositório?

Obrigado!!

**Comment by tiagobentotst** [comment]
O 2399 corresponde ao https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-service/src/main/resources/exemplos/tsv_termino.json

A retificação funciona como nos outros... Muda de "NORMAL" para "RETIFICACAO" e informa o protocolo do evento a ser retificado

**Comment by marcelo225** [comment]
@thiagoacioly, então o sobra para este [arquivo](https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-service/src/main/resources/exemplos/desligamento.json) para o S2299, correto?

**Comment by tiagobentotst** [comment]
Exato!

**Comment by marcelo225** [comment]
Obrigado, @thiagoacioly.
