### ISSUE TITLE
campo duplicado (dataEnvio e dtaEnvio)

### ISSUE THREAD

**Issue by lanabia** [tst-labs/esocial#149]
Olá, os dois campos dtaEnvio e dataEnvio das informações dos eventos se referem ao mesmo dado, não? Caso sim, é interessante retirar e manter o padrão `dta*` já utilizado em outros campos.

"enviosEvento":[1 item
0:{7 items
"id":370
"lote":{8 items
"id":111
"estado":{...}2 items
"codigoResposta":{...}4 items
"dataEnvio":1559761709000
"protocolo":"1.2.201906.0000000000001336533"
"retorno":"<eSocial xmlns="http://www.esocial.gov.br/schema/lote/eventos/envio/retornoEnvio/v1_1_0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"> <retornoEnvioLoteEventos> <ideEmpregador> <tpInsc>1</tpInsc> <nrInsc>09499757</nrInsc> </ideEmpregador> <ideTransmissor> <tpInsc>1</tpInsc> <nrInsc>09499757000146</nrInsc> </ideTransmissor> <status> <cdResposta>201</cdResposta> <descResposta>Lote Recebido com Sucesso.</descResposta> </status> <dadosRecepcaoLote> <dhRecepcao>2019-06-05T16:01:57.533</dhRecepcao> <versaoAplicativoRecepcao>0.1.0-A0366</versaoAplicativoRecepcao> <protocoloEnvio>1.2.201906.0000000000001336533</protocoloEnvio> </dadosRecepcaoLote> </retornoEnvioLoteEventos> </eSocial>"
"resposta":{...}4 items
"dtaEnvio":1559761709000
}

:)

**Comment by tiagobentotst** [comment]
Tem razão. Por algum motivo o campo ficou duplicado.
Já vamos subir uma correção.
