### ISSUE TITLE
Evento S2400 - Evento não reconhecido pelo eSocial-GOV

### ISSUE THREAD

**Issue by marcelo225** [tst-labs/esocial#151]
@thiagoacioly , blz.
Pergunta... vi que na raiz do projeto, no item "Eventos não periódicos", o evento S2400 não foi implementado pelo eSocial-GOV:

S-2400 | Cadastro de Benefícios Previdenciários - RPPS | 2.5 | Feito | Evento não reconhecido pelo eSocial-GOV
-- | -- | -- | -- | --

Tentei mandar um exemplo e deu o seguinte erro:

![image](https://user-images.githubusercontent.com/4791314/59124475-15e3ca00-8936-11e9-8d06-cb9244808c4b.png)

Isso seria um problema lá no e-social por não ter implementado esse evento? Tem alguma previsão para que o Serpro implemente esse evento?

Obrigado!!

**Comment by tiagobentotst** [comment]
Isso... Não está disponível no eSocial-Gov ainda

**Comment by marcelo225** [comment]
Obrigado, @thiagoacioly.
