### ISSUE TITLE
Problemas ao incluir um CNPJ de órgão não público

### ISSUE THREAD

**Issue by hugopgodoy** [tst-labs/esocial#152]
Mesmo problema da [issue](https://github.com/tst-labs/esocial/issues/114)

É, não encontrei uma forma de incluir um empregador na produção restrita se não for um CNPJ de órgão público.

> Obs: Estamos desenvolvendo uma folha de pagamento para um órgão público, mas para validar nossos eventos estamos usando um certificado da nossa empresa.

Desta forma, me deparei com o mesmo problema da quantidade de dígitos para órgãos não públicos já no retorno da requisição:

```json
"errosProcessamento": [
  {
    "id": 2,
    "descricao": "O CNPJ completo somente pode ser utilizado por órgãos públicos, os demais empregadores deverão informar somente o CNPJ base (8 primeiros dígitos do CNPJ).\nAção Sugerida: Se o empregador for um ente da administração direta federal o campo Número de Inscrição 'nrInsc' deve ter tamanho de 14 dígitos exatos. Caso contrário, o campo 'nrInsc' deve ter tamanho de 8 dígitos exatos.",
    "localizacao": "",
    "tipoErroProcessamento": {
      "id": 1,
      "descricao": "Erro"
     },
     "codMensagem": 646
},
```

Ao editar o parâmetro `esocialjt.cnpj-empregador` de `esocial/config/application.properties`, `nrInsc` e `referencia` do _body_ do POST de ocorrência com o CNPJ com apenas os 8 dígitos temos o seguinte erro no log da aplicação:

```xml
<codigo>402</codigo>
<descricao>The 'Id' attribute is invalid - The value 'ID1072282582019080614575400001"&gt;&lt;ide' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:ID' - The '"' character, hexadecimal value 0x22, cannot be included in a name.
</descricao>
```

Desta forma, editei o código fonte e "chumbei", apenas para teste, o parâmetro CNPJ da geração do ID do evento com o CNPJ completo

```java
public String gerarId(String cnpj) {
  LocalDateTime date = LocalDateTime.now();
  String seq = String.format("%05d", sequencial.proximo());
  DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyyMMddHHmmss");
  return "ID107228258000199" + date.format(formatter).replace("+", "") + seq;
}
```

e retorna o seguinte erro no log da app:

```xml
<codigo>607</codigo>
<descricao>O número de inscrição do transmissor deverá ser igual ao CNPJ/CPF do certificado utilizado para o envio do lote.
</descricao>
```

Preciso de ajuda para conseguir incluir um empregador (cnpj) de um órgão não público no ambiente restrito para dar sequencia na validação dos nossos eventos sem ter que solicitar para o órgão que estamos trabalhando um certificado A1. Alguém já passou por isso?

**Comment by rataodobanhado** [comment]
Aqui eu resolvi mexendo no gerarId também... coloquei essa linha antes do return:

		//caso seja o CNPJ base acrescenta zeros para completar o tamanho
		if (cnpj.length() == 8) cnpj = cnpj + "000000";

E no application.properties tanto o esocialjt.cnpj-empregador quanto esocialjt.nrInscIdeTransmissor estão com o número de CNPJ completo.

**Comment by hugopgodoy** [comment]
Muito obrigado! deu certo, mas foi por conta do `esocialjt.nrInscIdeTransmissor` que estava desabilitado.

**Comment by henriquemeira** [comment]
Fazendo um teste com uma empresa PJ geral (não pública) obtive o mesmo erro.
É preciso fazer alguma configuração em application.properties?

erro:

`<retornoEnvioLoteEventos>
esocial-jt-service | <status>
esocial-jt-service | <cdResposta>402</cdResposta>
esocial-jt-service | <descResposta>Lote Incorreto - Schema Inválido.</descResposta>
esocial-jt-service | <ocorrencias>
esocial-jt-service | <ocorrencia>
esocial-jt-service | <codigo>402</codigo>
esocial-jt-service | <descricao>The 'Id' attribute is invalid - The value 'ID1xxxxxxxx2019120322491700001"&gt;&lt;ide' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:ID' - The '"' character, hexadecimal value 0x22, cannot be included in a name.</descricao>
esocial-jt-service | <tipo>1</tipo>
esocial-jt-service | </ocorrencia>
esocial-jt-service | </ocorrencias>
esocial-jt-service | </status>
esocial-jt-service | </retornoEnvioLoteEventos>`

**Comment by henriquemeira** [comment]
Também é necessário definir o parametro: esocialjt.tpInscIdeTransmissor=1
