### ISSUE TITLE
Dúvida - Novos envios - EFD-REINF

### ISSUE THREAD

**Issue by lanabia** [tst-labs/esocial#153]
Olá, como vocês planejam a continuidade do projeto com as novas regras de envio pelo EFD-REINF? A API irá englobar este novo sistema de envio?

https://www.contabeis.com.br/artigos/5591/a-nova-efd-reinf-3-0/

Se possível, gostaríamos muito de entrar com contato direto com vocês (e-mail: lana.mesquita@tce.ce.gov.br).

Obrigada!

**Comment by tiagobentotst** [comment]
Olá,

neste projeto não está previsto o EFD-REINF. Ainda não avaliamos como será a implementação das obrigações referente a ele, mas é certo que será tratado em um serviço separado.

**Comment by lanabia** [comment]
Tudo bem. Obrigada pela resposta!
