### ISSUE TITLE
Atualização para NT 15-2019

### ISSUE THREAD

**Issue by lanamesquita** [tst-labs/esocial#155]
Olá, gostaríamos de saber se há alguma previsão para atualização dos leiautes conforme a nota técnica 15-2019.

Alterações -> http://www.normaslegais.com.br/legislacao/esocial-nota-tecnica-15-2019-revisada.pdf

**Comment by tiagobentotst** [comment]
Boa tarde,
por enquanto não estamos trabalhando neste projeto, mas assim que saírem as definições para órgãos públicos iremos retomá-lo.

**Comment by tiagobentotst** [comment]
Foi atualizado para a versão S-1.0
