### ISSUE TITLE
[Dúvida] Certificado Digital

### ISSUE THREAD

**Issue by CristianoAndrade350** [tst-labs/esocial#159]
Pessoa bom dia, gostaria de tirar uma dúvida, sou novo na área e estou em busca de uma API que me traga de alguma forma um vínculo empregatício de uma pessoa ou lista de funcionários de uma determinada empresa.
Achei a API do e-social, porém a documentação deles não me ajudou muito, e achei essa API de vocês.
No caso do Certificado, o que é necessário é comprar aquele e-CPF ou e-CNPJ?
Caso não seja um local para dúvidas por favor avise-me =)
Obrigado.

**Comment by rafaelluciodeveloper** [comment]
Bom dia, acho que essa api não vai servi pra vc ...essa informação vc não teria como ter acesso através de nenhuma API.essa api do esocial serve apenas para envio e consulta de eventos enviados referente ao eSocial.

**Comment by tiagobentotst** [comment]
Rafael está correto. Esta api é para o empregador que deseja enviar os eventos para o eSocial para cumprir suas obrigações trabalhistas

**Comment by CristianoAndrade350** [comment]
Que pena pessoal, muito obrigado, ajudou muito nessas dúvidas.
