### ISSUE TITLE
Interesse da SEPLAG

### ISSUE THREAD

**Issue by fhcfer** [tst-labs/esocial#165]
Boa tarde

Meu nome é Fernanda Figueiredo, estou responsável, junto com o Ivan Ávila, pela implantação do eSocial no estado de Minas Gerais. Em nome da Secretaria de Planejamento e Gestão do Estado, queríamos dizer que estamos interessados em utilizar o projeto eSocial-JT como estratégia paliativa de mensageria para o envio dos eventos iniciais e de tabelas do eSocial. Dessa forma, temos os seguintes questionamentos: 
- O que o estado precisa fazer para solicitar o acesso a esse sistema? Qual os primeiros passos que devemos tomar?
- É necessário formalizar de que maneira? Qual o caminho para o início dessa utilização?

Atenciosamente. A resposta pode ser mandada por aqui e se puderem me avisar pelo e-mail f*@p*.mg.gov.br também me ajudaria bastante. Muito obrigada.

**Comment by platbr** [comment]
Aparentemente este software tem intenção de se tornar livre uma vez que está disponibilizando aqui todo o código fonte, porém não existe nenhum tipo de licença de software livre vinculada a ele.
Talvez seja o caso de definir uma licença de forma que todos possam usá-lo sem eventuais restrições.
