### ISSUE TITLE
Escala horizontal/certificados

### ISSUE THREAD

**Issue by lbotton** [tst-labs/esocial#170]
Bom dia.
A construção de um serviço de assinatura seria preponderante para um cenário de escala horizontal com necessidade de utilização de mais de um certificado?
Obrigado pela atenção.

**Comment by tiagobentotst** [comment]
A princípio só é possível usar um certificado por instalação, mas pode-se usar várias instalações em seu ambiente, cada uma com um certificado. Pra cada uma  delas teria que ter uma instância ou esquema de banco de dados separada
