### ISSUE TITLE
Geração de chave

### ISSUE THREAD

**Issue by antoniobenaion** [tst-labs/esocial#171]
Boa tarde!

Alguém saberia me informar como devo proceder para gerar a chave do e-social (arquivo .pfx), por favor?

Desde já grato pela atenção.

Atenciosamente,

Antonio.

**Comment by tiagobentotst** [comment]
Boa tarde, desculpe a demora para responder.

A nossa solução trabalha com certificado tipo A1, ICP Brasil, ou seja, precisa ter o Certificado Raiz Brasileiro em sua cadeia de certificados. Esse é um produto que deve ser comprado em empresas específicas do setor. Aconselho a pesquisar no Google pois terão bastante opções. No caso de órgãos públicos, é preciso seguir os processos normais de compra.

Existem algumas propriedades de ambiente no projeto para configurar o tipo de certificado (application.properties)

```
   {
      "name": "esocialjt.arquivoCertificado",
      "type": "java.lang.String",
      "description": "Caminho para o arquivo do certificado digital ICP Brasil A1"
    },
    {
      "name": "esocialjt.tipoCertificado",
      "type": "java.lang.String",
      "description": "Tipo do certificado: pkcs12 ou jks"
    },
    {
      "name": "esocialjt.aliasCertificado",
      "type": "java.lang.String",
      "description": "Alias do certificado. Se vazio, tentará usar o primeiro alias disponível no certificado."
    },
    {
      "name": "esocialjt.senhaCertificado",
      "type": "java.lang.String",
      "description": "Senha do certificado digital"
    },
    {
      "name": "esocialjt.arquivoCacerts",
      "type": "java.lang.String",
      "description": "Caminho para o arquivo Cacerts"
    },
```

Se a sua dúvida é em relação aos tipos de chave e como converter de um para outro, talvez isso possa ajudar:

https://stackoverflow.com/questions/6307886/how-to-create-pfx-file-from-certificate-and-private-key
