### ISSUE TITLE
Divergência CNPJ

### ISSUE THREAD

**Issue by rlgdsa** [tst-labs/esocial#172]
Boa tarde, parabéns a todos pela iniciativa do projeto! 

Estou com uma pequena dificuldade para o evento s1000, quando preciso enviar a ocorrência com CNPJ **base** (8 caracteres) e certificado digital.

Dá erro: _O número de inscrição do transmissor deverá ser igual ao CNPJ/CPF do certificado utilizado para o envio do lote_.

Pelo postman, quando coloco no "nrInsc" o CNPJ na **integra** (14 caracteres) (casos apenas de Emp.Públicas)
recebo este: 

"protocolo": "1.2.202105.0000000000059682583"
"desResposta": "Lote recebido com sucesso"

Eventos processados: {PROCESSADO COM ERRO=1}

"descricao": "CNPJ inválido. O CNPJ completo somente pode ser utilizado por órgãos públicos, os demais empregadores deverão informar somente o CNPJ base (8 primeiros dígitos do CNPJ).\nAção Sugerida: Se o empregador for um ente da administração direta federal, estado ou município, o campo Número de Inscrição 'nrInsc' deve ter tamanho de 14 dígitos exatos. Caso contrário, o campo 'nrInsc' deve ter tamanho de 8 dígitos exatos."

Estou confuso, pois quando envio o cnpj com 8 caracteres no "nrInsc", nem processa o lote, e reclama da divergência do CNPJ com o certificado digital e com 14 caracteres envia mas critica o tipo da empresa! 

usando: java 8, tomcat 9, postman, postgress 13, certificado Serasa, produção restrita.

Podem dar uma iluminação?

Grato.

**Comment by tiagobentotst** [comment]
Boa tarde, desculpe a demora para responder.

É preciso mudar também o cnpj no arquivo `application.properties` 
```esocialjt.cnpj-empregador=00000000000```

É possível mudar também nas variáveis de ambiente do sistema ou outras formas de sobreposição do Spring Boot

**Comment by rlgdsa** [comment]
> Boa tarde, desculpe a demora para responder.
> 
> É preciso mudar também o cnpj no arquivo `application.properties`
> `esocialjt.cnpj-empregador=00000000000`
> 
> É possível mudar também nas variáveis de ambiente do sistema ou outras formas de sobreposição do Spring Boot


Boa tarde Tiago,

Obrigado pelo retorno!

Eu consegui resolver, colocando no arquivo application.properties o ideTransmissor com o CNPJ completo (14c), achei que era apenas para os casos de Representante Legal de Empresa, mas pode ser do tipo=1 CNPJ tb... 
Assim consegui transmitir o CNPJ na "ocorrência" com 8 posições!
