### ISSUE TITLE
Erro - CNPJ do Ente Federativo Responsável divergente do CNPJ cadastrado na RFB

### ISSUE THREAD

**Issue by mauriciomac** [tst-labs/esocial#173]
Prezados Srs.,

em primeiro lugar, parabenizo a iniciativa deste projeto! Certamente será de grande utilidade a todos os órgãos públicos inseridos no contexto do eSocial.

Estamos testando o sistema em nossa autarquia e, ao que parece, tivemos sucesso com o evento S-1000: criamos o "xml" a partir de um "json", o assinamos digitalmente, nos comunicamos com o consórcio e procedemos com o envio. Entretanto, recebemos o seguinte erro no retorno: "O CNPJ do Ente Federativo Responsável preenchido está divergente do CNPJ cadastrado no Sistema CNPJ da RFB. Ação Sugerida: Corrija a informação ou compareça à unidade local da RFB para regularizar a situação.".

Conforme supracitado, somos uma autarquia e, consultando o nosso CNPJ na página da RFB, temos a resposta de que nosso "ENTE FEDERATIVO RESPONSÁVEL (EFR)" é a "UNIÃO"; todavia, nesta mesma consulta não nos é informado QUAL seria o CNPJ da UNIÃO para que pudéssemos colocá-lo no campo "cnpjEFR". Já tentamos três sem sucesso:
    
União Federal (PGF) - CNPJ 05.489.410/0001-61    
União Federal (PGFN) - CNPJ 00.394.460/0001-41    
União Federal (AGU) - CNPJ 26.994.558/0001-23

Portanto, pergunto: onde estamos errando?

Obrigado!

**Comment by tiagobentotst** [comment]
Tenta esse: 
`"cnpjEFR": "41414323000109"`

**Comment by mauriciomac** [comment]
FUNCIONOU! Obrigado, Tiago!
