### ISSUE TITLE
TABELA_CARGO

### ISSUE THREAD

**Issue by rlgdsa** [tst-labs/esocial#175]
Boa tarde a todos,

Estou tentando enviar uma admissão de funcionário, e o erro retornado é:

- O valor informado no campo deverá existir na Tabela de CBO. Tabela de Cargos.

Tentei incluir um cargo pelo Json de exemplo "tabela_cargo_alteracao.json" quando verifiquei na implementação, que não existe TABELA_CARGO para o TipoOcorrencia

"JSON parse error: Cannot deserialize value of type `br.jus.tst.esocial.ocorrencia.TipoOcorrencia` from String \"TABELA_CARGO\": value not one of declared Enum instance names: [AFASTAMENTO_TEMPORARIO, REINTEGRACAO, ALTERACAO_CONTRATUAL, REMUNERACAO_RGPS, DESLIGAMENTO, FECHAMENTO_PERIODICOS, REABERTURA_PERIODICOS, TSV_ALTERACAO_CONTRATUAL, REMUNERACAO_RPPS, ADMISSAO_TRABALHADOR, BENEFICIO_RPPS, TSV_TERMINO, TABELA_ESTABELECIMENTO, INFORMACOES_EMPREGADOR, TABELA_LOTACAO, EXCLUSAO, TSV_INICIO, TABELA_RUBRICA, ALTERACAO_CADASTRAL, TABELA_PROCESSO, PAGAMENTOS]; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `br.jus.tst.esocial.ocorrencia.TipoOcorrencia` from String \"TABELA_CARGO\": value not one of declared Enum instance names: [AFASTAMENTO_TEMPORARIO, REINTEGRACAO, ALTERACAO_CONTRATUAL, REMUNERACAO_RGPS, DESLIGAMENTO, FECHAMENTO_PERIODICOS, REABERTURA_PERIODICOS, TSV_ALTERACAO_CONTRATUAL, REMUNERACAO_RPPS, ADMISSAO_TRABALHADOR, BENEFICIO_RPPS, TSV_TERMINO, TABELA_ESTABELECIMENTO, INFORMACOES_EMPREGADOR, TABELA_LOTACAO, EXCLUSAO, TSV_INICIO, TABELA_RUBRICA, ALTERACAO_CADASTRAL, TABELA_PROCESSO, PAGAMENTOS]\n at [Source: (PushbackInputStream); line: 2, column: 20] (through reference chain: br.jus.tst.esocial.ocorrencia.OcorrenciaDTO[\"tipoOcorrencia\"])",

É provável que ainda estejam implementando.
Podem dar uma orientação? 

Desde já obrigado!

**Comment by tiagobentotst** [comment]
A Tabela Cargo foi removida na versão S-1.0

https://github.com/tst-labs/esocial#eventos-de-tabelas

**Comment by rlgdsa** [comment]
Entendi Tiago.

No S-2200, o cargo deve referenciar um código que esteja na tabela de CLASSIFICAÇÃO BRASILEIRA DE OCUPAÇÕES.

http://www.mtecbo.gov.br/cbosite/pages/home.jsf

Obrigado!
