### ISSUE TITLE
Duvida na exclusão produção restrita - órgão público

### ISSUE THREAD

**Issue by tonyamorim** [tst-labs/esocial#179]
Boa Noite,

Uso para órgão público e não esta excluindo as informações mesmo usando o [http://localhost:8080/esocial-jt-service/producao-restrita/acoes/limpar](url), ele limpa a base local, mas no esocial não exclui.
 
Depois da exclusão ele continua com o erro:

**_"Já existe no sistema registro com mesmo código de identificação (chave) em período de vigência conflitante com o período informado no registro atual.
Ação Sugerida: O evento somente pode ser recepcionado se não existir outro evento para a tabela com o mesmo código de identificação (chave) em período de vigência conflitante com o período informado no evento atual.
Certifique-se que o código de identificação e os períodos informados estejam corretos."_**

Alguem pode me ajudar?

**Comment by tiagobentotst** [comment]
Em nosso ambiente está funcionando.
Verifique por gentileza se os parâmetros no `application.properties` estão corretos, como o CNPJ do empregador e as informações de certificado digital.

**Comment by tonyamorim** [comment]
Obrigado amigo,

Ainda não consegui, quando executo /esocial-jt-service/producao-restrita/acoes/limpar, recebi o protocolo e fui consultar, o resultado foi: 
`                                        
<codigo>174</codigo>
<descricao>A data de ocorrência do evento '01/10/2010' deve ser igual ou posterior ao início da obrigatoriedade deste evento 
   '01/01/2017' para o empregador ao eSocial. Para confirmar a data de obrigatoriedade do empregador, verifique o cronograma 
   disponível no site https://portal.esocial.gov.br/.
</descricao>`

estou sem entender porque estou limpando

**Comment by tonyamorim** [comment]
Resolvi,
o problema é que para órgãos públicos o cnpj tem apenas o 8 primeiro digitos, e no 
esocialjt.cnpj-empregado do application.properties tem que esta completo por causa do certificado.
Só consegui limpar chamando dessa maneira: http://localhost:8080/esocial-jt-service/producao-restrita/acoes/limpar?cnpj=12345678, passando os 8 primeiros dígitos na url.

Obrigado
