### ISSUE TITLE
CNPJ inválido no formulário S-1000

### ISSUE THREAD

**Issue by edteixeira** [tst-labs/esocial#183]
Prezados,

Estamos fazendo os testes de envio aqui no Minstério Público do Estado de Rondônia e ainda estamos bem no começo. No caso, estamos ainda no formulário S-1000. 
Por sermos um órgão público de natureza jurídica 108-2, de acordo com o manual, devemos preencher o campo "nrInsc" com 14 dígitos e também o "cnpjEFR" também com 14 dígitos. Conforme json abaixo:

{
 "tipoOcorrencia": "INFORMACOES_EMPREGADOR",
 "referencia": "04381083",
 "operacao": "INCLUSAO",
 "retificarRecibo": null,
 "dataOcorrencia": 1627331782,
 "dadosOcorrencia": {
    "tipo": ".InformacoesEmpregador",
    "ideEmpregador": {
        "tpInsc": 1,
        "nrInsc": "04381083000167"
    },
    "infoEmpregador": {
        "idePeriodo": {
            "iniValid": "2021-01",
            "fimValid": null
        },
            "novaValidade": null,
            "infoCadastro": {
                "classTrib": "01",
                "indCoop": 0,
                "indConstr": 0,
                "indDesFolha": 0,
                "indOpcCP": null,
                "indPorte": null,
                "indOptRegEletron": 0,
                "cnpjEFR":"00394585000171",
                "dadosIsencao": null,
                "infoOrgInternacional": null
            }
        }
    }
}

Pois bem, estamos seguindo o manual e ao enviarmos, recebemos o erro:

[
    {
        "id": 1,
        "tipoOcorrencia": "INFORMACOES_EMPREGADOR",
        "referencia": "04381083",
        "operacao": "INCLUSAO",
        "retificarRecibo": null,
        "dataOcorrencia": 1522180917526,
        "dataRecebimento": 1627322164429,
        "dadosOcorrencia": {
            "tipo": ".InformacoesEmpregador",
            "ideEmpregador": {
                "tpInsc": 1,
                "nrInsc": "04381083000167"
            },
            "infoEmpregador": {
                "idePeriodo": {
                    "iniValid": "2021-01",
                    "fimValid": null
                },
                "novaValidade": null,
                "infoCadastro": {
                    "classTrib": "01",
                    "indCoop": 0,
                    "indConstr": 0,
                    "indDesFolha": 0,
                    "indOpcCP": null,
                    "indPorte": null,
                    "indOptRegEletron": 0,
                    "cnpjEFR": "00394585000171",
                    "dadosIsencao": null,
                    "infoOrgInternacional": null
                }
            }
        },
        "evento": {
            "id": 1,
            "ocorrencia": 1,
            "estado": {
                "id": 4,
                "descricao": "PROCESSADO COM ERRO"
            },
            "idEvento": "ID1043810830001672021072617560500001",
            "tipoEvento": {
                "desTipo": "Informações do Empregador/Contribuinte/Órgão Público",
                "grupoTipoEvento": {
                    "id": 1,
                    "descricao": "Eventos de Tabelas"
                },
                "codTipo": 1000
            },
            "enviosEvento": [
                {
                    "id": 1,
                    "lote": {
                        "id": 1,
                        "estado": {
                            "id": 4,
                            "descricao": "PROCESSADO COM ERRO"
                        },
                        "codigoResposta": {
                            "id": 11,
                            "desResposta": "Lote recebido com sucesso",
                            "codGrupoResposta": 1,
                            "codResposta": 201
                        },
                        "dtaEnvio": 1627322168207,
                        "protocolo": "1.2.202107.0000000000080681024",
                        "retorno": "<eSocial xmlns=\"http://www.esocial.gov.br/schema/lote/eventos/envio/retornoEnvio/v1_1_0\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n<retornoEnvioLoteEventos>\n<ideEmpregador>\n<tpInsc>1</tpInsc>\n<nrInsc>04381083000167</nrInsc>\n</ideEmpregador>\n<ideTransmissor>\n<tpInsc>1</tpInsc>\n<nrInsc>04381083000167</nrInsc>\n</ideTransmissor>\n<status>\n<cdResposta>201</cdResposta>\n<descResposta>Lote Recebido com Sucesso.</descResposta>\n</status>\n<dadosRecepcaoLote>\n<dhRecepcao>2021-07-26T14:56:08.103</dhRecepcao>\n<versaoAplicativoRecepcao>0.1.95</versaoAplicativoRecepcao>\n<protocoloEnvio>1.2.202107.0000000000080681024</protocoloEnvio>\n</dadosRecepcaoLote>\n</retornoEnvioLoteEventos>\n</eSocial>",
                        "resposta": {
                            "id": 11,
                            "desResposta": "Lote recebido com sucesso",
                            "codGrupoResposta": 1,
                            "codResposta": 201
                        }
                    },
                    "codRespostaProcessamento": {
                        "id": 4,
                        "desResposta": "Erro no conteúdo do evento.",
                        "codGrupoResposta": 2,
                        "codResposta": 401
                    },
                    "dtaGeracaoEvento": 1627257600000,
                    "versao": "\"S-1.0\"",
                    "erroInterno": null,
                    "errosProcessamento": [
                        {
                            "id": 1,
                            "descricao": "CNPJ inválido. O CNPJ completo somente pode ser utilizado por órgãos públicos, os demais empregadores deverão informar somente o CNPJ base (8 primeiros dígitos do CNPJ).\nAção Sugerida: Se o empregador for um ente da administração direta federal, estado ou município, o campo Número de Inscrição 'nrInsc' deve ter tamanho de 14 dígitos exatos. Caso contrário, o campo 'nrInsc' deve ter tamanho de 8 dígitos exatos.",
                            "localizacao": "",
                            "tipoErroProcessamento": {
                                "id": 1,
                                "descricao": "Erro"
                            },
                            "codMensagem": 646
                        }
                    ]
                }
            ],
            "nrRecibo": null
        }
    }
]

Ao mudar o campo "nrInsc" para apenas os 8 primeiros dígitos do CNPJ, na tentativa de sanar o problema, o erro muda para 401.

Tentamos contato com a equipe responsável no esocial, porém não obtivemos sucesso. 

Gostaríamos de saber estamos da forma correta e é um bug na API do esocial ou se estamos fazendo errado.

Gratos

**Comment by tiagobentotst** [comment]
É necessário mudar também a propriedade no arquivo `application.properties`
Veja por gentileza se está relacionado com o que foi relatado em #172 e #173

**Comment by edteixeira** [comment]
Seguimos a orientação do #172
<https://github.com/tst-labs/esocial/issues/172>, mas não resolveu o
problema, apesar do problema ser exatamente igual.

Em ter., 27 de jul. de 2021 às 12:56, Tiago Bento ***@***.***>
escreveu:

**Comment by edteixeira** [comment]
Grato pela resposta. 
Seguimos as orientações do #172 pois o problema é idêntico, porém não resolveu.

**Comment by edteixeira** [comment]
[RESOLVIDO]
Alteramos o arquivo application.properties inserindo as linhas no início:

esocialjt.cnpj-empregador=00000000 (CNPJ 08 dígitos) 
esocialjt.tpInscIdeTransmissor=1
esocialjt.nrInscIdeTransmissor=00000000000000 (CNPJ 14 dígitos)
