### ISSUE TITLE
Certificado A3

### ISSUE THREAD

**Issue by tonyamorim** [tst-labs/esocial#197]
Bom dia,

Gostaria de saber se existe alguma possibilidade de usar o certificado A3

**Comment by hednilson** [comment]
Uma possibilidade seria alterar o método Certificado. conforme abaixo.
````

**Comment by tiagobentotst** [comment]
Este projeto não tem previsão de atender essa necessidade por enquanto. Mas pode-se usar a solução apresentada pelo hednilson como referência.
