### ISSUE TITLE
Limpar dados do esocial-gov/local

### ISSUE THREAD

**Issue by Claison** [tst-labs/esocial#199]
Boa tarde! ja tentei utilizar em duas maquinas diferentes mas quando mando o POST para limpar ele esta dando erro e não faz nada, alguém pode me ajudar?

**Comment by Claison** [comment]
Bom dia rafael, sim teve a conexão, dai eu tento fazer os testes, e me retornou erro de preenchimento, ai usei o comando que faz a limpeza, tem um erro, e permanece o erro. você consegue nos dar uma força para colocar pra funcionar, (63) 99220-4605

**Comment by tiagobentotst** [comment]
Qual é o erro que aparece?
