### ISSUE TITLE
Contribuição Slack

### ISSUE THREAD

**Issue by thiagonevestjdft** [tst-labs/esocial#20]
Boa tarde.

Sobre esse trecho do documento de contribuição: **"Qualquer órgão ou indivíduo que esteja ativamente contribuindo ou usando o eSocial-jt deve se juntar ao nosso time nas conversas via Slack. Caso você esteja interessando em contribuir ou saber mais, solicite sua inclusão em nosso Workspace."**

Gostaria de solicitar a inclusão de uma equipe do **TJDFT**, como devo proceder?

Obrigado.

**Comment by calimaborges** [comment]
@thiagonevestjdft, o CONTRIBUTING está desatualizado. Migramos nosso canal de comunicação em tempo real para o Rocket Chat do TST. Criei um merge request para atualizar o CONTRIBUTING e respondi sua dúvida no Rocket Chat.
