### ISSUE TITLE
Evento S-2400  e derivados

### ISSUE THREAD

**Issue by RodrigoGuerato** [tst-labs/esocial#211]
Boa tarde!

Na documentação consta que o evento S-2400 não é aceito pelo eSocial-GOV.
Pelo que entendi do manual de orientação, os orgãos públicos que pagam este tipo de beneficio precisam enviar o cadastro de seus beneficiários a partir de 22/11/2021.

| Evento | Nome Evento                                                           | Versão | Situação     | Resultado do envio para a produção restrita |
| ------ | --------------------------------------------------------------------- | ------ | ------------ | ------------------------------------------- |
| S-2400 | Cadastro de Benefícios Previdenciários - RPPS                         | S-1.0  | Feito        | NÃO ACEITO NA PRESENTE DATA                 |

Esta no planejamento a adequação para o envio deste evento?

Obrigado!

Rodrigo Guerato

**Comment by tiagobentotst** [comment]
Sim, está na próxima etapa de desenvolvimento

**Comment by RodrigoGuerato** [comment]
Thiago, bom dia.

Há uma previsão de entrega dessa etapa de desenvolvimento? Seria apenas para uma previsão interna nossa aqui na prefeitura.

Obrigado novamente.

**Comment by tiagobentotst** [comment]
Será em breve, mas não temos uma previsão exata...

**Comment by tiagobentotst** [comment]
A última versão já implementa os eventos novos
