### ISSUE TITLE
Erro 500 

### ISSUE THREAD

**Issue by Kennedi1313** [tst-labs/esocial#213]
Esse erro indica indisponibilidade do servidor de produção restrita?

![image](https://user-images.githubusercontent.com/13836595/142448794-9898d12e-7557-43a5-aa8d-0c140c432360.png)

**Comment by Kennedi1313** [comment]
Alguém já passou por esse erro? Estou enfrentando isso no dia dos testes para a subida... até ontem estava tudo certo.

**Comment by tiagobentotst** [comment]
Testei agora e está com o mesmo problema. Algo no ambiente de Produção Restrita

**Comment by Kennedi1313** [comment]
Ta bem, era mais pra saber se o problema era no meu código ou se é no serviço deles... Vou fechar esse tópico, obrigado!
