### ISSUE TITLE
Layout da requisição do estabelecimento com multiplo processos judiciais

### ISSUE THREAD

**Issue by Matheuscruztj** [tst-labs/esocial#221]
Boa noite,
Como ficaria o layout do json se o estabelecimento possuir multiplos processos judiciais?
Gera várias requisições cada qual com seu processo respectivo? 

Exemplo abaixo, com somente 1 processo:
"dadosEstab": {
    "cnaePrep": xxxx,
    "aliqGilrat": {
        "aliqRat": 1,
        "fap": 1,
        "aliqRatAjust": 1,
        "procAdmJudRat":{
            ...
        },
        "procAdmJudFap":{
            ...
        }
    }
}

**Comment by tiagobentotst** [comment]
Pelo layout do evento, o eSocial só aceita 1 processo RAT e um processo FAT

**procAdmJudRat**: Processo administrativo/judicial relativo à alíquota RAT
**procAdmJudFap**: Processo administrativo/judicial relativo ao FAP

https://www.gov.br/esocial/pt-br/documentacao-tecnica/leiautes-esocial-nt-03-2021-html/index.html#evtTabEstab

**Comment by Matheuscruztj** [comment]
Obrigado.
