### ISSUE TITLE
Rubrica (devolução de vale transporte) - Evento S1010

### ISSUE THREAD

**Issue by Matheuscruztj** [tst-labs/esocial#232]
Possuo a rubrica de 'devolução de vale transporte', que é uma ajuda de custo (valor positivo, bonificado) onde o valor não precisa ser declarado para imposto de renda. Não posso colocar a coluna 'codIncIRRF' como null, qual seria a melhor opção que posso colocar?

Levando em consideração a tabela de referência.
https://www.gov.br/esocial/pt-br/documentacao-tecnica/leiautes-esocial-nt-01-2021-html/index.html/tabelas.html#21

Obs: pesquisando os valores que são geralmente utilizados, são 09 e 11.

**Comment by tiagobentotst** [comment]
Seria mais interessante tirar essa dúvida com a área de negócio da sua empresa/órgão e depois fazer testes de alguns envios na produção restrita
