### ISSUE TITLE
Evento TABELA_CARGO inexistente

### ISSUE THREAD

**Issue by antoniobenaion** [tst-labs/esocial#234]
Boa tarde,

Ao tentar enviar uma requisição JSON para o evento TABELA_CARGO, recebi a resposta a seguir:

"{
    "timestamp": 1641934010601,
    "status": 400,
    "error": "Bad Request",
    "message": "JSON parse error: Cannot deserialize value of type `br.jus.tst.esocial.ocorrencia.TipoOcorrencia` from String \"TABELA_CARGO\": value not one of declared Enum instance names: [AFASTAMENTO_TEMPORARIO, REINTEGRACAO, ALTERACAO_CONTRATUAL, REMUNERACAO_RGPS, DESLIGAMENTO, FECHAMENTO_PERIODICOS, REABERTURA_PERIODICOS, TSV_ALTERACAO_CONTRATUAL, REMUNERACAO_RPPS, ADMISSAO_TRABALHADOR, BENEFICIO_RPPS, TSV_TERMINO, TABELA_ESTABELECIMENTO, INFORMACOES_EMPREGADOR, TABELA_LOTACAO, EXCLUSAO, TSV_INICIO, TABELA_RUBRICA, ALTERACAO_CADASTRAL, TABELA_PROCESSO, PAGAMENTOS]; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `br.jus.tst.esocial.ocorrencia.TipoOcorrencia` from String \"TABELA_CARGO\": value not one of declared Enum instance names: [AFASTAMENTO_TEMPORARIO, REINTEGRACAO, ALTERACAO_CONTRATUAL, REMUNERACAO_RGPS, DESLIGAMENTO, FECHAMENTO_PERIODICOS, REABERTURA_PERIODICOS, TSV_ALTERACAO_CONTRATUAL, REMUNERACAO_RPPS, ADMISSAO_TRABALHADOR, BENEFICIO_RPPS, TSV_TERMINO, TABELA_ESTABELECIMENTO, INFORMACOES_EMPREGADOR, TABELA_LOTACAO, EXCLUSAO, TSV_INICIO, TABELA_RUBRICA, ALTERACAO_CADASTRAL, TABELA_PROCESSO, PAGAMENTOS]\n at [Source: (PushbackInputStream); line: 2, column: 20] (through reference chain: br.jus.tst.esocial.ocorrencia.OcorrenciaDTO[\"tipoOcorrencia\"])",
    "path": "/esocial-jt-service/ocorrencias"
}"

Ao verificar a classe tipoOcorrencia, observei que este evento TABELA_CARGO não consta do enum da referida classe.

**Comment by tiagobentotst** [comment]
A tabela de cargo foi excluída na versão S-1.0

**Comment by antoniobenaion** [comment]
Obrigado pelo esclarecimento, Tiago.
