### ISSUE TITLE
Erro json parse - evento 2200

### ISSUE THREAD

**Issue by Matheuscruztj** [tst-labs/esocial#250]
Boa noite,
Peguei o exemplo do evento 2200 para envio e está retornando a seguinte mensagem de erro:

{
    "timestamp": 1644440821836,
    "status": 400,
    "error": "Bad Request",
    "message": "JSON parse error: Missing type id when trying to resolve subtype of [simple type, class br.jus.tst.esocial.ocorrencia.dados.DadosOcorrencia]: missing type id property 'tipo' (for POJO property 'dadosOcorrencia'); nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Missing type id when trying to resolve subtype of [simple type, class br.jus.tst.esocial.ocorrencia.dados.DadosOcorrencia]: missing type id property 'tipo' (for POJO property 'dadosOcorrencia')\n at [Source: (PushbackInputStream); line: 89, column: 3] (through reference chain: br.jus.tst.esocial.ocorrencia.OcorrenciaDTO[\"dadosOcorrencia\"])",
    "path": "/esocial-jt-service/ocorrencias"
}

Obs: o mesmo se repete com o evento de alteração cadastral.

**Comment by Kennedi1313** [comment]
Boa noite, já passei por esse erro quando estava usando uma versão antiga da api. Na versão mais nova eles retiraram o campo do id, então eles atualizaram nos exemplos também. Se vc tiver usando uma versão da api que não seja a ultima, sugiro também usar uma versão mais antiga do exemplo, que terá o id.
No caso do S2200 o id é uma string ".Admissao" dentro de dadosOcorrencia.

**Comment by Matheuscruztj** [comment]
Testei com a nova versão e deu certo.
