### ISSUE TITLE
Limpar Produção Restrita.

### ISSUE THREAD

**Issue by zacariasgsn** [tst-labs/esocial#251]
Bom dia,

Estou utilizando o serviço para limpar a produção restrita, tem o retorno de sucesso, mas quando tento enviar novamente o evento S -1000 está retornando a seguinte mensagem de erro:

537: Já existe no sistema registro com mesmo código de identificação (chave) em período de vigência conflitante com o período informado no registro atual. Ação Sugerida: O evento somente pode ser recepcionado se não existir outro evento para a tabela com o mesmo código de identificação (chave) em período de vigência conflitante com o período informado no evento atual. Certifique-se que o código de identificação e os períodos informados estejam corretos.

Alguém sabe explicar o que pode está acontecendo? Será que está limpando realmente os dados que foram enviados anteriormente?

**Comment by zacariasgsn** [comment]
Boa tarde,

Ainda estamos com problema, quando utilizamos o serviço para limpar a produção restrita, ele apaga os registros das tabelas locais. Porém, quando tentamos enviar o mesmo evento, recebemos a mensagem com o código 537.
Para enviar novamente o evento, temos que alterar o período de vigência do mesmo.

**Comment by tiagobentotst** [comment]
Estou passando algum valor de CNPJ como parâmetro da URL `/acoes/limpar`? Vocês fazem a chamada POST usando qual aplicativo?

**Comment by zacariasgsn** [comment]
Prezados, obrigado pelo apoio.

O problema era exatamente o CNPJ informado, não estávamos passando por parâmetro o CNPJ para o endpoonit.
Com isso, a nossa aplicação estava pegando o CNPJ setado no properties que é o CNPJ completo ( com 11 dígitos)
Depois que setamos como parâmetro o CNPJ reduzido (com 8 dígitos) o serviço se comportou de forma correta e 
apagou os eventos na base do e-social também.
