### ISSUE TITLE
MAPEAMENTO DOS LAYOUTS PARA OS NÚMEROS DE EVENTO

### ISSUE THREAD

**Issue by wwebdevelop** [tst-labs/esocial#257]
Olá, pessoal. Primeiro, parabéns pelo trabalho desenvolvido!

Não sei já há este tipo de informação, mas seria interessante termos um mapeamento dos layouts para os códigos de eventos. Por exemplo: 2205, 2206...e assim por diante.
Assim, ficaria mais fácil de identificar a qual evento se refere o layout de exemplo.

Por que não consigo, por exemplo, identificar facilmente qual destes layouts se refere ao evento 2205 apenas pela descrição do arquivo.

Acredito que no link abaixo seria o local mais apropriado:
https://github.com/tst-labs/esocial/tree/master/src/esocial-jt-service/src/main/resources/exemplos
Na coluna do meio da página que abre no link acima poderia haver a informação do código do evento.

**Comment by tiagobentotst** [comment]
Olá, 
Infelizmente o xsd fornecido na documentação do eSocial usa apenas o nome dos eventos, por isso seguimos o mesmo padrão.

Se te ajuda, a classe abaixo faz a correlação entre o nome e o número do evento:
https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-service/src/main/java/br/jus/tst/esocialjt/dominio/TipoEvento.java
