### ISSUE TITLE
Evento 2200 - dtIniAbono - campo inválido

### ISSUE THREAD

**Issue by Matheuscruztj** [tst-labs/esocial#258]
Boa noite,
Estou realizando uma requisição do evento 2200 e o campo dtIniAbono está sendo recusando quando o cadIni = "N", indAbonoPerm = "S", tpProv = 6.

O próprio manual do eSocial, informa: Não informar se [tpProv](https://www.gov.br/esocial/pt-br/documentacao-tecnica/leiautes-esocial-html/index.html#2200_vinculo_infoRegimeTrab_infoEstatutario_tpProv) for diferente de [5, 8, 10].

Se passar dtIniAbono como nulo, recebo: "Campo de preenchimento obrigatório: Data de início do abono permanência".
Como posso resolver o problema?

Obs: existe algum tempo mínimo que deva esperar para que seja lançado um evento de afastamento?

**Comment by tiagobentotst** [comment]
Fizemos alguns testes recentes com esse campo... Pelo que entendi está relacionado com a data dtIniAbono. 
Se cadIni=S essa data não pode ser posterior ao início da obrigatoriedade (nesse caso indAbonoPerm = "N" e dtIniAbono=null).
Se cadIni=N precisa ter uma sucessão de vínculo com data anterior a dtIniAbono (ou mudança de CPF). Caso contrário, tambémindAbonoPerm = "N" e dtIniAbono=null.

Resumindo, essa regra é bem chata então tem que ficar atento ao manual e fazer por tentativa e erro na produção restrita.

`Existe algum tempo mínimo que deva esperar para que seja lançado um evento de afastamento? ` Não vi nenhuma recomendação até o momento, mas é melhor tirar essa dúvida diretamente com o ministério responsável pelo eSocial (Gov).
