### ISSUE TITLE
Atributo "tipo" não encontrado

### ISSUE THREAD

**Issue by wwebdevelop** [tst-labs/esocial#266]
Estou testando o evento 2200, segundo este layout: https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-service/src/main/resources/exemplos/admissao_trabalhador.json

Na observação diz: Não é mais necessário um campo tipo no json de DadosOcorrencia

Entretanto, ao tentar enviar um json para a produção restrita, retorna o seguinte erro justamente reclamando do atributo "tipo" que está ausente. Segue:

{
"timestamp":1647346336271,
"status":400,
"error":"Bad Request",
"message":"JSON parse error: Missing type id when trying to resolve subtype of [simple type, class br.jus.tst.esocial.ocorrencia.dados.DadosOcorrencia]: 
missing type id property 'tipo' (for POJO property 'dadosOcorrencia'); 
nested exception is com.fasterxml.jackson.databind.exc.InvalidTypeIdException: 
Missing type id when trying to resolve subtype of [simple type, class br.jus.tst.esocial.ocorrencia.dados.DadosOcorrencia]: 
missing type id property 'tipo' (for POJO property 'dadosOcorrencia')\n at [Source: (PushbackInputStream); line: 1, column: 2471] 
(through reference chain: br.jus.tst.esocial.ocorrencia.OcorrenciaDTO[\"dadosOcorrencia\"])","path":"/esocial-jt-service-dev/ocorrencias"}

**Comment by tiagobentotst** [comment]
Verifique por gentileza se estão rodando a última versão

**Comment by wwebdevelop** [comment]
Sim. Estamos rodando a última versão!
Atualizamos ela até a segunda vez para fins de assegurar que é a última versão.

**Comment by wwebdevelop** [comment]
Ao incluir o campo "tipo" no JSON, foi processado com sucesso.
