### ISSUE TITLE
PROBLEMA ENTRE OS ENVIOS S-1000 E S-2200

### ISSUE THREAD

**Issue by wwebdevelop** [tst-labs/esocial#268]
Tentamos enviar 1 JSON com dados de 1 trabalhador (S-2200) na "produção restrita" e nos foi retornado o seguinte:
- Processado com erro.
- "É necessário existir informação cadastral do empregador para o período. Ação Sugerida: Verificar se já foi enviado um evento de cadastramento do empregador."

Ou seja, tudo dá entender que falta o envio do S-1000 e S-1005. 
Então procedemos o envio para a "produção restrita" do mesmo JSON S-1000 que foi enviado para a "produção" e que foi processado com sucesso na ocasião na produção. E nos foi retornado o seguinte.

- Processado com erro.
- "Já existe no sistema registro com mesmo código de identificação (chave) em período de vigência conflitante com o período informado no registro atual. Ação Sugerida: O evento somente pode ser recepcionado se não existir outro evento para a tabela com o mesmo código de identificação (chave) em período de vigência conflitante com o período informado no evento atual. Certifique-se que o código de identificação e os períodos informados estejam corretos."

Em suma, no envio do S-2200 o serviço emitiu a crítica de não haver o evento S-1000. Quando então reenviamos o S-1000 disse que já tinha, mas que o período de vigência tem conflito. Porém, não sabemos identificar o conflito...se é entre datas, quais datas. Segue o nosso S-1000:

{"tipoOcorrencia":"INFORMACOES_EMPREGADOR","referencia":"04789665000187","operacao":"INCLUSAO","dataOcorrencia":1626859122000,"dadosOcorrencia":{"tipo":".InformacoesEmpregador","ideEmpregador":{"tpInsc":1,"nrInsc":"04789665"},"infoEmpregador":{"idePeriodo":{"iniValid":"2021-07","fimValid":null},"novaValidade":null,"infoCadastro":{"classTrib":85,"indCoop":0,"indConstr":0,"indDesFolha":0,"indOpcCp":null,"indPorte":null,"indOptRegEletron":1,"cnpjEFR":"05054861000176","dadosIsencao":null,"infoOrgInternacional":null}}}}

Tentamos também limpar a "produção restrita" e reenviar tudo novamente. Mas foi apresentada a mesma problemática.

**Comment by wwebdevelop** [comment]
Alguma "luz"?
Estive pesquisando na internet a sugestão é excluir o envio já feito do S-1000 e reenviar.
Mas não terá impacto negativo?...pois estarei enviando, agora, um evento de forma atrasada (S-1000) que foi enviada em tempestivamente no passado.

**Comment by tiagobentotst** [comment]
Na produção restrita é possível apagar e enviar novamente quantas vezes quiser, sem nenhum prejuízo. Caso não esteja conseguindo limpar, tente fazer essa solução: https://github.com/tst-labs/esocial/issues/251#issuecomment-1069526451

**Comment by wwebdevelop** [comment]
Vou olhar, pois mesmo chamando a rotina de limpar a produção restrita o problema persiste.

**Comment by anaazzoni** [comment]
Ainda em ambiente de produção restrita, nos testes de envido da 2200 estamos com problemas para enviar as datas convertidas em milisegundo ANTES  de 1970, por exemplo minha data de nascimento,  26/05/1969. O retorno é um valor NEGATIVO (-18997200000). Poderia nos ajudar ?

**Comment by wwebdevelop** [comment]
Este é comportamento correto da conversão. Veja:
https://www.epochconverter.com/

Os meus testes com datas negativas foram bem sucedidos. Você chegou a
tentar enviar ou só viu negativo o campo e achou estranho?

Tente enviar. Não deve dar erro.

**Comment by wwebdevelop** [comment]
Tiago, ao alterar o CNPJ do declarante, conseguimos enviar o evento. Conforme sua indicação #251 .
Grato pela atenção e ajuda!

**Comment by anaazzoni** [comment]
> 

Sim enviamos, deu erro e associamos ao valor negativo, mas o problema era outro.

**Comment by wwebdevelop** [comment]
Resolvido então. Abs.

**Comment by anaazzoni** [comment]
Na tabela de Resumo de Registros, para o evento 2200, por exemplo tem a coluna CONDIÇÃO: temos O="OBRIGATÓRIO", N="NÃO OBRIGATÓRIO", OC="OBRIGATÓRIO SE EXISTIR", e qual seria o significado de F ?? veja no layout do campo horContratual.

**Comment by wwebdevelop** [comment]
Aconselho você a não seguir o layout oficial do e-social para montar a
estrutura JSON que conterá os dados, pois como você mesmo já observou, ela
é incompatível com a estrutura JSON adotada pelo TST.

Se você fizer isso, no momento de testar o envio terá bastantes problemas,
pois campos mudam levemente de nomenclatura, outros são omitidos, outros já
são calculados pelo sistema do TST.

Então como estou trabalhando?
Estou tomando como base os exemplos de layout que o TST disponibilizou.
Construo o JSON e faço ajustes necessários.

Por exemplo, ao construir todo layout do evento 2200 e testar envio recebi
críticas do sistema quanto a campos faltantes. Abri até uma issue separada
para informar a questão.

Outro ponto a se observar é que, quando seu envio entra na situação "em
fila",  o sistema de mensageria altera o arquivo json que você enviou
originalmente. Acrescentando diversos campos e informações.

Este arquivo alterado fica no atributo "conteudo_envio" do response do
sistema à requisição de envio.
