### ISSUE TITLE
Gerando Id's Antigos

### ISSUE THREAD

**Issue by maik001** [tst-labs/esocial#270]
Estou tentando enviar uma ocorrência do evento S-1299 de FECHAMENTO_PERIODICOS, porém ao invés de ele gerar um novo id da requisição ela gera um id de uma requisição já antiga.
Obs: Estou usando o postman.

**Comment by tiagobentotst** [comment]
Verifique como está a sequence `SEQ_OCORRENCIA_ID` no banco de dados

**Comment by maik001** [comment]
bigint	64	2	0	1	1	99999999	1	NO

**Comment by maik001** [comment]
Eu consegui enviar a maioria dos eventos aqui e foi beleza, porém 3 eventos em específico (que eu testei) estão com esse problema, que são o S-1020 de Lotação, o 1299 de fechamento dos eventos periódicos e o 1298 de reabertura dos eventos periódicos.

Descrição do SEQ_OCORRENCIA_ID:
 sequence_catalog -> bigint
 sequence_schema -> public
 sequence_name -> seq_ocorrencia_id 
 numeric_precision -> bigint
 numeric_precision_radix -> 2
 numeric_scale -> 0
 start_value -> 1
 minimum value -> 1
 maximum_value -> 99999999
 increment -> 1
 cycle_option -> NO

**Comment by maik001** [comment]
Bom dia, eu estou com por volta de 800 registros de ocorrências no banco e alguns eventos estão gerando ids de requisições já enviadas, gostaria de perguntar se já tem alguma atualização sobre esse problema?

**Comment by maik001** [comment]
Ok, obrigado pela resposta.
