### ISSUE TITLE
INCLUSÃO DE CAMPOS EXIGIDOS QUANDO DO ENVIO DO EVENTO S-2200

### ISSUE THREAD

**Issue by wwebdevelop** [tst-labs/esocial#274]
São eles:
- dtIniAbono
- cbofuncao
- nmFuncao
- acumCargo

No decorrer dos testes de envio para a produção restrita houve erros decorrentes da ausência destes campos no JSON enviado.
Ao analisar o JSON de layout para o evento, publicado no GitHub, notamos a falta destes campos.

Fica a sugestão. Abs

**Comment by tiagobentotst** [comment]
Não entendi, aqui estamos enviando normalmente com esses campos...

https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-dominio/src/main/java/br/jus/tst/esocial/dominio/vinculo/InfoEstatutario.java

https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-dominio/src/main/java/br/jus/tst/esocial/dominio/vinculo/InfoContrato.java

**Comment by wwebdevelop** [comment]
Fale, Tiago!
Estou baseando os trabalhos nos exemplos de layout disponibilizados no GitHub. Segue: https://github.com/tst-labs/esocial/tree/master/src/esocial-jt-service/src/main/resources/exemplos

Estes exemplos estão incompletos? Pois não são citados estes campos.

**Comment by tiagobentotst** [comment]
Esses exemplos contém um conjunto mínimo necessário de campos para ser processado com sucesso. Na prática deverão ser gerados os eventos de acordo com o manual do eSocial. Lá tem as condições de preenchimento de cada campo.

**Comment by wwebdevelop** [comment]
Sim, notei que faltam campos como por exemplo: sexoDep.
Ok
