### ISSUE TITLE
Actuator Health error 500

### ISSUE THREAD

**Issue by devhijazi** [tst-labs/esocial#277]
Olá, estou tentando iniciar a aplicação conforme explicado no readme seguindo 100% dos passos, porém ao verificar o estado do actuator ele informa no devtools um erro 500. ja nos logs do docker é mostrado 2 erros.

1- 403 forbbiden por conta do Maven 
2- Certificado A3 conforme aplicado na issue #269 e #197 não é encontrado.

além destes erros, ao entrar na pasta `src/` e utilizar o mvn clean install package encontro erros como cannot find symbol e module na hora de gerar o build....

**Comment by tiagobentotst** [comment]
O erro do maven provavelmente é por conta da versão do Java... A aplicação usa JDK 8, dá uma olhada qual versão está instalada na sua máquina...

O certificado infelizmente é necessário para subir a aplicação
