### ISSUE TITLE
Erro no envio Evento S-2400

### ISSUE THREAD

**Issue by DouglasDeFarias** [tst-labs/esocial#278]
Bom dia, estou gerando o envio "json" igual ao modelo de vocês, mas está dando este erro:

============================================================================

2022 - 03 - 31 10: 00: 08.270 WARN 6136-- - [nio - 8080 - exec - 3].w.s.m.s.DefaultHandlerExceptionResolver: Resolved[org.springframework.http.converter.HttpM
    essageNotReadableException: JSON parse error: Cannot deserialize value of type `br.jus.tst.esocial.ocorrencia.TipoOcorrencia` from String "CADASTRO_BE
    NEFICIARIO_INI": value not one of declared Enum instance names: 
	[AFASTAMENTO_TEMPORARIO, REINTEGRACAO, ALTERACAO_CONTRATUAL, REMUNERACAO_RGPS, DESLIGAMENTO, 
	FECHAMENTO_PERIODICOS, REABERTURA_PERIODICOS, TSV_ALTERACAO_CONTRATUAL, REMUNERACAO_RPPS, 
	ADMISSAO_TRABALHADOR, BENEFICIO_RPPS, TSV_TERMINO, TABELA_ESTABELECIMENTO, INFORMACOES_EMPREGADOR, 
	TABELA_LOTACAO, EXCLUSAO, TSV_INICIO, TABELA_RUBRICA, ALTERACAO_CADASTRAL, TABELA_PROCESSO, PAGAMENTOS];
    nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `br.jus.tst.esocial.ocorrencia.TipoOc
    orrencia` from String "CADASTRO_BENEFICIARIO_INI": value not one of declared Enum instance names: [AFASTAMENTO_TEMPORARIO, REINTEGRACAO, ALTERACAO_CON
        TRATUAL, REMUNERACAO_RGPS, DESLIGAMENTO, FECHAMENTO_PERIODICOS, REABERTURA_PERIODICOS, TSV_ALTERACAO_CONTRATUAL, REMUNERACAO_RPPS, ADMISSAO_TRABALHADO
        R, BENEFICIO_RPPS, TSV_TERMINO, TABELA_ESTABELECIMENTO, INFORMACOES_EMPREGADOR, TABELA_LOTACAO, EXCLUSAO, TSV_INICIO, TABELA_RUBRICA, ALTERACAO_CADAST
        RAL, TABELA_PROCESSO, PAGAMENTOS]
    at[Source: (PushbackInputStream);
        line: 1, column: 19](through reference chain: br.jus.tst.esocial.ocorrencia.OcorrenciaDTO["tipoOcorrencia"])]

============================================================================

Analisando isso e vendo no projeto, não aparece no arquivo TipoOcorrencia.java :

public enum TipoOcorrencia {

	INFORMACOES_EMPREGADOR(InformacoesEmpregador.class), 
	TABELA_ESTABELECIMENTO(TabelaEstabelecimento.class), 
	TABELA_RUBRICA(TabelaRubrica.class), 
	TABELA_LOTACAO(TabelaLotacao.class), 
	TABELA_PROCESSO(TabelaProcesso.class), 
	ADMISSAO_TRABALHADOR(Admissao.class),
	ALTERACAO_CADASTRAL(AltCadastral.class),
	ALTERACAO_CONTRATUAL(AltContratual.class),
	AFASTAMENTO_TEMPORARIO(AfastTemp.class),
	DESLIGAMENTO(Deslig.class),
	REINTEGRACAO(Reintegr.class),
	TSV_INICIO(TSVInicio.class),
	TSV_ALTERACAO_CONTRATUAL(TSVAltContr.class),
	TSV_TERMINO(TSVTermino.class),
	REMUNERACAO_RGPS(Remun.class),
	REMUNERACAO_RPPS(RmnRPPS.class),
	BENEFICIO_RPPS(BenPrRP.class),
	PAGAMENTOS(Pgtos.class),
	REABERTURA_PERIODICOS(ReabreEvPer.class),
	FECHAMENTO_PERIODICOS(FechaEvPer.class),
	EXCLUSAO(Exclusao.class);

Como proceder, pois estou com o projeto atualizado.
Agradeço desde já.

**Comment by tiagoben** [comment]
Verifique se você está com a última versão do projeto

https://github.com/tst-labs/esocial/blob/master/src/esocial-jt-dominio/src/main/java/br/jus/tst/esocial/ocorrencia/TipoOcorrencia.java

**Comment by DouglasDeFarias** [comment]
Boa tarde Tiago, vou atualizar. Obrigado.
