### ISSUE TITLE
Demora no processamento de eventos no modo esocialjt.ambiente=PRODUCAO

### ISSUE THREAD

**Issue by rafaelgsilva91** [tst-labs/esocial#281]
Bom dia, desde o começo do mês quando vou processar eventos no modo `esocialjt.ambiente=PRODUCAO`, os eventos ficam em fila por horas, na imagem abaixo tem um exemplo onde os eventos foram processados e ficaram cerca de 2 horas em fila, e alguns nem processam, isso é normal? 
![image](https://user-images.githubusercontent.com/4140782/162454142-ea33084f-bb82-4a18-98fe-08df8fb673de.png)

**_Gostaria também de agradecer a disponibilização dessa API, que com certeza vai ajudar muitas equipes pequenas como a nossa da Defensoria de MS._**

**Comment by tiagobentotst** [comment]
Boa tarde,
Isso não deveria demorar tanto assim... Aparece alguma mensagem no log? Muitas vezes o ambiente do eSocial do governo federal está indisponível, por isso fica muito tempo aguardando voltar.

**Comment by rafaelgsilva91** [comment]
@tiagobentotst Boa tarde, a mensagem do log é apenas "Existem X eventos na fila." e não sai disso, no produção restrita está OK, eu vou tentando aqui, qualquer coisa dou um retorno.

**Comment by rafaelgsilva91** [comment]
Bom dia @tiagobentotst, resolvi o problema, como pode ver na imagem, tem 496 eventos em processamento, em algum momento eu devo ter parado a aplicação ou alterado algo no banco, pois a fila ficou sempre no limite, não conseguindo processar mais nada, a solução foi alterar o status desses eventos para o status de *ERRO* diretamente no banco.
