### ISSUE TITLE
S-1207 - Número benefício

### ISSUE THREAD

**Issue by Matheuscruztj** [tst-labs/esocial#282]
Boa tarde,
Pode repassar algum link de referência ou sobre o que trata esse campo de número do benefício, existe alguma tabela na internet onde possa pesquisar por esse valor?

**Comment by rafaelgsilva91** [comment]
Boa tarde, a única explicação que encontrei está disponível no [Manual de Fev. 2022]( https://www.gov.br/esocial/pt-br/documentacao-tecnica/manuais/mos-s-1-0-consolidada-ate-a-no-s-1-0-10-2022-com-marcacoes.pdf).
Onde o número do benefício deve ser único no declarante, podendo ser, por exemplo, o número do 
processo/protocolo, matrícula etc.
