### ISSUE TITLE
Lentidão no envio do Evento S-2200

### ISSUE THREAD

**Issue by DouglasDeFarias** [tst-labs/esocial#283]
Boa tarde,

É normal demorar muito para o eSocial devolver o retorno? Pois enviei às 11:00 e consultando pela URL no browser está "EM FILA".

Um trecho do json:

 "estado": {
            "id": 1,
            "descricao": "EM FILA"
        },
        "idEvento": "ID1194823870000002022041208260300005",
        "tipoEvento": {
            "desTipo": "Trabalhador Sem Vínculo de Emprego/Estatutário - Início",
            "grupoTipoEvento": {
                "id": 2,
                "descricao": "Eventos Não Periódicos"
            },

Sendo que parao mesmo evento mas para outros órgãos aqui retorna rápido, até isolamos a nossa interface e chamamos direto pelo conector de vocês, mas fica nisso "EM FILA".

Vi em um issue fechado que pode demorar mesmo, se for imagina com todo mundo enviando. 
Agradeço desde já.

**Comment by rafaelgsilva91** [comment]
Boa tarde @DouglasDeFarias , você olhou esse issue #281 ? Acredito que seja o mesmo problema.

**Comment by DouglasDeFarias** [comment]
Boa tarde Rafael, vou dar uma olhada.
Obrigado.
