### ISSUE TITLE
Recibo - processado com erro - S-2300

### ISSUE THREAD

**Issue by Matheuscruztj** [tst-labs/esocial#284]
Bom dia,
Após enviar um cadastro com cep inválido, o eSocial aceitou e gerou recibo, com advertência.
Na est_evento, a coluna 'cod_estado' está 4.

O meu filtro de sucesso atualmente do sistema está quando o evento está com 'cod_estado' = 3 e com número de recibo existente. Precisaria mudar ele ou esse reajuste do 'cod_estado' pode ser feito no sistema (java)?

**Comment by reutman** [comment]
Olá! Como resolveu essa situação? Estamos com o mesmo problema, por enquanto, de maneira provisória, estamos considerando os eventos com o nrRecibo preenchido como sucesso, mesmo retornando o código do estado 4.

**Comment by Matheuscruztj** [comment]
Como eles geraram recibo, eles foram processados com sucesso. Então para correção completa, deve ser ajustado o que ele informa de pendência/observação nos detalhes e dependendo do evento, ele ser cancelado pelo S-3000 e reenviado novamente para validação de se as inconformidades foram resolvidas.

**Comment by reutman** [comment]
Certo, é possível realizar um S-3000 ou mesmo uma retificação, porém acredito que o status esteja errado, já que o status 4 indica processado com erro, e não processado com advertência, e isso pode causar inconsistência no tipo de status dos sistemas origem. O que acha sobre essa situação @tiagobentotst ?

**Comment by tiagobentotst** [comment]
Essa situação está no backlog para alteração. Por enquanto pode fazer como o Matheus sugeriu.
