### ISSUE TITLE
Dúvida - O que informar no campo "referencia": ??

### ISSUE THREAD

**Issue by elsonlondon** [tst-labs/esocial#285]
Bom dia, sou do Tribunal de Justiça de Mato Grosso e surgiu uma dúvida aqui... O que devemos informar no campo "referencia":  previsto no layout do TST? Qual a finalidade desse campo? Obrigado.

**Comment by Matheuscruztj** [comment]
Bom dia,
Não sei se ele possui um significado direto para o evento em si. Mas estou utilizando ele como um identificador nos eventos.
Ex: 1010 - código da rubrica, 2200 - matrícula do funcionário.

**Comment by rafaelgsilva91** [comment]
Boa tarde, também utilizado como identificador.

**Comment by tiagobentotst** [comment]
Exato. Pode ser usado como um identificador para controlar nos sistemas de origem.
