### ISSUE TITLE
Dúvida no Certificado Digital

### ISSUE THREAD

**Issue by DouglasDeFarias** [tst-labs/esocial#286]
Boa tarde,

Gostaria de tirar uma dúvida sobre o certificado digital no ambiente de PRODUÇÃO, usando um do tipo E_CNPJ, envia normalmente.
Mas com E-CPF estão EM FILA e não sabemos se funciona mesmo, já vimos no E-CAC e está com todas as permissões, tipo com procuração, etc.

Existe alguma trava nesse projeto por E_CPF? Espero que não. Até vimos no suporte deles mas ainda sem sucesso.

No ambiente de produção restrita funcionou normalmente.

**Comment by rafaelgsilva91** [comment]
Boa tarde, o certificado é  do tipo A1? Pois é pré-requisito do projeto a utilização de um certificado A1, mesmo para testes.

**Comment by DouglasDeFarias** [comment]
Boa tarde Rafeal, é sim do tipo A1. Mas estamos tentando enviar de uma autarquia.

**Comment by rafaelgsilva91** [comment]
Entendi, no **PRODUCAO_RESTRITA** foi tudo Ok?

**Comment by DouglasDeFarias** [comment]
Sim, normal

Em qua, 20 de abr de 2022 17:40, Rafael Gouveia da Silva <
***@***.***> escreveu:

**Comment by DouglasDeFarias** [comment]
Boa tarde, a solução:

Na codificação existe uma validação para verificar se já foram enviados EVENTOS anteriores e aqui como órgão público foi enviado as informações com o certificado A3 e não tinha este projeto ainda do TST.
Por isso não estavam na tabela do tst.

Foi só cadastrar.
