### ISSUE TITLE
S-2300 - infoMandElet (falta campos)

### ISSUE THREAD

**Issue by Matheuscruztj** [tst-labs/esocial#287]
Boa tarde,
O evento S-2300, quando o codCateg for 304, dentro do atributo 'infoMandElet' estão faltando os campos:
categOrig
cnpjOrig
matricOrig
dtExercOrig

![erro-eventos2300](https://user-images.githubusercontent.com/34069604/164269161-b240b068-686d-4d0d-98c7-a48d2fe9e1aa.png)

**Comment by rafaelgsilva91** [comment]
Boa tarde, conforme última versão consolidada do Layout simplificado S-1.0, esses campos não são informados.

![image](https://user-images.githubusercontent.com/4140782/164313987-9064b9b7-e268-4199-a382-329a78c075f9.png)

**Comment by Matheuscruztj** [comment]
Estamos utilizando a última versão do TST e a mensagem de erro foi do eSocial, no caso a documentação deve estar desatualizada, poderia fazer o envio de teste para validação?

**Comment by rafaelgsilva91** [comment]
Fiz o envio de teste e realmente o **esocial-gov** retorna esse erro, então podemos esperar novas versões ou seguir as orientações para envio de um **PR**.

**Comment by tonyamorim** [comment]
O layout em PDF tem todos os campos, o em HTML não tem. Estão diferentes.

**Comment by tiagobentotst** [comment]
A versão corrigida submetida pelo @Matheuscruztj foi para a master.
