### ISSUE TITLE
[Dúvida] - Layouts S2200/S2300 - trabalhador/nascimento/dtNascto

### ISSUE THREAD

**Issue by rodolfocop** [tst-labs/esocial#288]
Boa tarde, nos envios a PRODUÇÃO está apresentando erro abaixo nos dois Layouts.

Erros
Código: 176

A data de nascimento do trabalhador está divergente da base da Receita Federal. Verifique se os dados foram digitados corretamente ou oriente o trabalhador para procurar uma unidade conveniada da Receita Federal para atualizar os dados.

/eSocial/evtAdmissao/trabalhador/nascimento/dtNascto

Fizemos varias tentativas com o campo com os seguintes formatos abaixo:

"YYYY-MM-DD"
"1650486821" -> Convert epoch ( A data informada é meramente ilustrativa )
"YYYY-MM-DDT00:00:00.000"

Poderiam nos auxiliar neste cenário?

Obrigado!

**Comment by tiagobentotst** [comment]
Tenta usar o timestamp em milissegundos: Ex.: 126846000000

**Comment by hednilson** [comment]
Os campos do tipo data estão sendo mapeados para o tipo Calendar nas classes de domínio.
Caso seja informada uma data no formato "YYYY-MM-DD" ela será considerada como "YYYY-MM-DD 00:00:00.000" em UTC. Durante a conversão dessas datas para XML, em XMLGregorianCalendarMapper, caso a JVM esteja rodando com timezone GMT-3, a data json "2022-04-22"  é convertida para um Calendar "2022-04-22 00:00:00.000+00:00" e o código calendar.getTime() (linha 22) passa a representar a data "2022-04-21 21:00:00.000-03:00". Isso faz com que a data no XML seja passada como "2022-04-21". Para contornar o problema, passamos a gerar os campos do tipo data no json com o fuso GMT-3, pois é mais legível que um timestamp em milisegundos. No exemplo acima, se o campo no json for preenchido com "2022-04-22 00:00:00.000-03:00" a data no XML será configurada corretamente. Outra alternativa seria alterar as classes de domínio para usar LocalDate em vez de Calendar e tratar os campos de datas no formato padrão "YYYY-MM-DD".
