### ISSUE TITLE
GeradorId.java gerou o mesmo "ID repetido" em 4 registros diferentes

### ISSUE THREAD

**Issue by felipecarvalhotjmg** [tst-labs/esocial#290]
Prezados, boa tarde.  Tivemos um **ERRO** estranho, em que o Transmissor gerou o **mesmo** ID para 4 registros(eventos) diferentes.
O que pode ter ocorrido ? 
O ato de enviar os eventos foi muito rápido e usou algum CACHE do evento que gera o ID  ?  rs
A data e hora, com segundos, até pode ser a mesma, mas o **SEQUENCIAL** deveria ser diferente !!!

**ERRO** :  'ID1211545540000002022042509340700001' is already used as an ID.

`<cdResposta>402</cdResposta>`
`<descResposta>Lote Incorreto - Schema Inválido.</descResposta>`
(. . .) 
`<codigo>402</codigo>`
`<descricao>'ID1211545540000002022042509340700001' is already used as an ID.</descricao>`

**![Transmissor_GeradorID_ERRO_ID_repetido](https://user-images.githubusercontent.com/104387044/165155377-73185016-0417-4437-9901-0ca75ad1f581.jpg)** 

**Query para exibir o total de registros com a ID repetida :** 
SELECT  Count(*) as total, txt_id_evento 
from  esocial.est_evento
GROUP BY txt_id_evento
HAVING Count(*)>1

-------------------------------------------------------------
| total | txt_id_evento                                                    |
| 4	  | ID1211545540000002022042509340700001 | 
-------------------------------------------------------------

**Query dos eventos com a mesma ID :** 
SELECT  *
from  esocial.est_evento
where txt_id_evento = 'ID1211545540000002022042509340700001'

----------------------------------------------------------------------------------------
COD_EVENTO | COD_OCORRENCIA | COD_TIPO | COD_ESTADO | TXT_ID_EVENTO
---------------------------------------------------------------------------------------- 
17779	13280	1010	5	ID1211545540000002022042509340700001	
17800	13300	1010	5	ID1211545540000002022042509340700001	
17778	13279	1010	5	ID1211545540000002022042509340700001	
17798	13299	1010	5	ID1211545540000002022042509340700001	
----------------------------------------------------------------------------------------

O **arquivo** que gera o ID é : 
...\esocial-jt-service\src\main\java\br\jus\tst\esocialjt\xml\GeradorId.java

Vocês já tiveram problema com esse Gerador de ID ? 
Existe alguma alternativa para isso  ? 

Att.
Felipe Carvalho - TJMG

**Comment by tiagobentotst** [comment]
Teoricamente isso não deveria acontecer... Existe mais de uma instância da aplicação executando em paralelo?
