### ISSUE TITLE
Erro em loop eternamente

### ISSUE THREAD

**Issue by Kennedi1313** [tst-labs/esocial#291]
Boa noite pessoal, 
Essa noite subi uma instância do projeto (produção) após deixá-la down por uns dias porque o certificado tinha expirado. Nesse meio tempo atualizei o projeto pra uma versão bem mais recente. Porém um evento que estava na fila desde antes do certificado cair voltou a tentar ser executado, gerando um erro que entrou em loop. O erro é o seguinte:

![image](https://user-images.githubusercontent.com/13836595/165417825-082d2357-a9a6-4f7e-baa1-5e1955dae1f8.png)

Na real o erro nem importa tanto, isso provavelmente já foi corrigido, o problema é mesmo o loop... o sistema fica repetindo infinitamente a tentativa (falha) de fazer esse mesmo cast. 
A dúvida é: em casos assim que um evento entra em loop de erro eternamente, como fazer pra interromper esse loop? como mandar o sistema ignorar esse erro e continuar a execução normalmente?

Agradeço desde já qualquer conselho.

**Comment by tiagobentotst** [comment]
Bom dia,
realmente é uma situação bem incomum, não havíamos pensado nesse caso...
Sugiro tentar apagar o registro no banco de dados e enviar o evento novamente...
