### ISSUE TITLE
Pensionista enquadrado na regra EC 103/2019 - qual grupo?

### ISSUE THREAD

**Issue by mauriciomac** [tst-labs/esocial#293]
Prezados, 

temos pensionistas enquadrados na regra mais recente do ano de 2019 (EC 103/2019); entretanto, nos grupos citados na documentação do eSocial, tabela 25, não há previsão para essas regras.

Que código usar? Alguma dica?

**Comment by tiagobentotst** [comment]
Infelizmente não temos a resposta para esse tipo de questão. Sugiro entrar em contato com o Ministério ou com a área de negócio do seu órgão.
