### ISSUE TITLE
Falta de algumas validações nos eventos S-2405, S-2410, S-2420 e S-2418

### ISSUE THREAD

**Issue by reutman** [tst-labs/esocial#295]
Olá,

Identificamos que o evento S-2405, não possui a regra que verifica se existe algum evento S-2400 em fila ou processando na classe RegraCdBenefAlt. 
Somente existem as regras empregadorCadastrado e naoHaEventoTabelaEmFila.

O mesmo ocorre para o evento S-2410 que seguindo o padrão implementado em outros eventos, a regra RegraCdBenefIn deveria verificar se existe algum evento S-2400 em fila ou processando.

Os eventos S-2420 RegraCdBenTerm e S-2418 RegraReativBen também deveriam verificar se existem eventos S-2400 e S-2410 em fila ou processando.

**Comment by Matheuscruztj** [comment]
Boa noite,
Relacionado a essa verificação, implementada pelo sistema pode não possuir.
Mas o eSocial no momento que receber esse evento e tentar processa-lo, vai perceber que o evento X antecessor não foi processado ainda com sucesso e notificará com um erro.

Pode ser feita uma validação sobre o txt_referencia da ocorrência, com o txt_nr_recibo não nulo (sucesso). Assim só passando para o final do evento filho, se o pai tiver sido processado com sucesso e não tiver sido excluído pelo S-3000 também.

**Comment by tiagobentotst** [comment]
Como existem muitas regras de validação no eSocial, esta solução se preocupa somente em ordenar os envios que podem gerar uma inconsistência grave no RET. Caso o sistema de origem envie eventos fora da ordem esperada, o próprio eSocial recusa o evento e apresenta o erro relacionado. Assim o sistema de origem pode reenviar na ordem correta.
