### ISSUE TITLE
Correção - consulta de ocorrências sem evento

### ISSUE THREAD

**Issue by Matheuscruztj** [tst-labs/esocial#297]
Atualmente:
@NamedQuery(name = "Ocorrencia.ocorrenciasSemEvento", query = "SELECT o FROM Ocorrencia o where o.id NOT IN (SELECT e.ocorrencia.id FROM Evento e)")
Problema: em bases muitos grandes de envio, pode demorar em realizar essa consulta e assim atrasar o envio de cada lote.

Solução
@NamedQuery(name = "Ocorrencia.ocorrenciasSemEvento", query = "select o FROM Ocorrencia o left join Evento e on o.id = e.ocorrencia.id where e.id is null")
Explicação: fazendo o relacionamento começando pela ocorrência e se relacionado ao evento, utilizando a técnica do 'left', vai respeitar todas as entidades da ocorrência, assim filtrando os que tiverem com o id do evento como nulo pelo where.

**Comment by tiagobentotst** [comment]
Coloquei uma tarefa no backlog para analisar o caso

**Comment by tiagobentotst** [comment]
Foi pra master. Muito obrigado!
