### ISSUE TITLE
Erro de "Unrecognized field"

### ISSUE THREAD

**Issue by maik001** [tst-labs/esocial#310]
O log está informando o seguinte Erro:

ERROR 1 --- [nio-8080-exec-4] br.jus.tst.esocialjt.dominio.Ocorrencia  : Unrecognized field "regPt" (class br.jus.tst.esocial.dominio.tabela.estabelecimento.InfoTrab), not marked as ignorable (2 known properties: "infoPCD", "infoApr"]) at [Source: (String)"{"tipo":".TabelaEstabelecimento","ideEmpregador":{"tpInsc":1,"nrInsc":"06750525"},"infoEstab":{"ideEstab":{"tpInsc":1,"nrInsc":"06750525000120","iniValid":"2022-01"},"dadosEstab":{"cnaePrep":8411600,"infoTrab":{"regPt":0,"infoApr":{"contApr":0}}}}}"; line: 1, column: 221] (through reference chain: br.jus.tst.esocial.ocorrencia.dados.TabelaEstabelecimento["infoEstab"]->br.jus.tst.esocial.dominio.tabela.estabelecimento.InfoEstab["dadosEstab"]->br.jus.tst.esocial.dominio.tabela.estabelecimento.DadosEstab["infoTrab"]->br.jus.tst.esocial.dominio.tabela.estabelecimento.InfoTrab["regPt"])

**Comment by JaisonPeres** [comment]
Opa @maik001 chegou a fazer um teste de envio do S-1000 com sucesso?

**Comment by maik001** [comment]
Sim, já realizamos o envio do S-1000 com sucesso, este erro no log surgiu recentemente

**Comment by tiagobentotst** [comment]
O evento 1005 não tem mais essa propriedade regPt na útima versão
https://www.gov.br/esocial/pt-br/documentacao-tecnica/leiautes-esocial-nt-05-2022-html/index.html
