### ISSUE TITLE
Implmentação para Mappers

### ISSUE THREAD

**Issue by fernandoosorio** [tst-labs/esocial#311]
Pessoal, primeiramente gostaria de agradecer por terem disponibilizado esse projeto.

Estou tentando entender o código e há 2 meses atrás quando fiz o checkout existiam Implementações(ex: EmpregadorMapperImpl.java)  para os Mapper (ex: EmpregadorMapper.java). Baseado, naquela versão eu consegui enviar o evento S-1000. Agora tentar enviar do evento S-1005, existe no repositório apenas o arquivo TabelaEstabelecimentoMapper sem a implementação. 
Pergunto vocês abondarem essa abordagem? 

Para finalizar, informo que não estamos a API diretamente, mas fazendo ajustes diretamente no código para se adaptar ao nosso sistema de pessoal.

De já agradeço a atenção.

**Comment by tiagobentotst** [comment]
As classes de implementação dos Mappers (*MapperImpl.java) são geradas por um famework chamado mapstruct em tempo de compilação, por exemplo ao fazer um `mvn install`. Existe também um plugin no Eclipse que faz essa construção automática https://mapstruct.org/documentation/ide-support/

**Comment by fernandoosorio** [comment]
Muito Obrigado, Tiago
