### ISSUE TITLE
Registros na tabela EST_ENVIO_EVENTO não atualizados após processamento do LOTE

### ISSUE THREAD

**Issue by lucasbhti** [tst-labs/esocial#323]
Prezados,
sou analista no Tribunal de Justiça do Estado de Minas Gerais e utilizamos esta solução de integração há bastante tempo.

Ontem (05/10/22), por volta de meio-dia, tivemos vários lotes com eventos de remuneração (S-1202 e S-1207) que retornaram erros de processamento internos do eSocial.

Alguns dos lotes(EST_LOTE) foram atualizados para o COD_ESTADO=5, COD_RESPOSTA=NULL e TXT_ERRO_INTERNO com a seguinte mensagem:
**A solicitação não pode ser atendida devido a uma falha não identificada que pode ou não ser temporária.Favor tentar novamente mais tarde.Caso o erro permaneça por um período superior a 6 (seis) horas, favor acessar o Portal do eSocial através do endereço https://www.gov.br/esocial/pt-br/canais_atendimento. Na opção CONTATO, na seção EMPRESAS, selecione PRODUÇÃO EMPRESAS. Preencha o formulário sobre erro 301 informando o identificador do evento para rastreamento do erro. Obrigado.**

Nestes casos, novas tentativas de envio foram realizadas até que o retorno do eSocial no processamento do LOTE ficasse da seguinte forma:
COD_ESTADO=4, COD_RESPOSTA=13(Erro Servidor ESOCIAL) e, agora, TXT_ERRO_INTERNO=NULL.

Neste ponto, novas tentativas de envio(EST_ENVIO_EVENTO) não foram mais realizadas, contudo, os registros na tabela EST_ENVIO_EVENTO vinculados a estes EST_LOTE's não tiveram sua informação COD_RESPOSTA atualizada de forma a identificar este erro de processamento e, por sua vez, os registros na tabela EVENTO também não tiveram o COD_ESTADO atualizado, permanecendo "congelados" no estado "PROCESSAMENTO".

Desta forma não temos mais atualizações do processamento dos LOTES, uma vez que o fim de processamento com erro já foi assinalado em seu registro, mas este estado de erro não foi propagado para as tabelas EST_ENVIO_EVENTO e nem EST_EVENTO.

Temos milhares de ocorrências nesta situação.

- Este erro já é conhecido por vocês?
- Estamos avaliando alterar vis script direto no banco o estado nas tabelas EST_ENVIO_EVENTO e EST_EVENTO. Vocês tem alguma sugestão de correção para realizarmos nestes dados?
- Como devemos proceder para evitar que o problema volte a ocorrer?

Desde já agradecemos o apoio.

**Comment by tiagobentotst** [comment]
Bom dia Lucas,

Realmente não havíamos previsto esse tipo de erro no eSocial (todo dia uma novidade). Nesse caso específico, creio que é necessário fazer um script de banco para poder atualizar os registros e não ficar travado o envio de vocês. Iremos analisar a situação e avaliar como proceder se isso acontecer novamente.

**Comment by hednilson** [comment]
Bom dia.
Ocorreu uma situação semelhante ontem, 03/11/2022, por volta de 16h.
Um lote foi enviado com sucesso gerando número de protocolo.
O lote passou para o estado 2 (EM PROCESSAMENTO).
Quando o serviço tentou atualizar o estado do lote recebeu a seguinte resposta do eSocial:
`<eSocial>
<retornoProcessamentoLoteEventos>
<status>
<cdResposta>69</cdResposta>
<descResposta>
Não foi possível estabelecer conexão com o Sistema do CNPJ. A falha pode ser temporária, tente novamente mais tarde.
</descResposta>
</status>
</retornoProcessamentoLoteEventos>
</eSocial>`
Assim, os estados do lote e dos eventos não foram atualizados, impedindo que novos eventos/lotes fossem enviados.
Como solução de contorno, atualizamos o estado desse lote e seus eventos para 5 (ERRO) diretamente no banco de dados.
Seria interessante prever essas situações.
Desde já agradecemos.
