### ISSUE TITLE
Modelo JSON para Períodos Anteriores de Remuneração - "infoPerAnt"

### ISSUE THREAD

**Issue by fariasdouglas** [tst-labs/esocial#330]
Boa tarde,

Estamos com problemas no layout dos envios de remuneração para períodos anteriores (S-1200). Poderiam por favor disponibilizar um modelo de layout de vários períodos anteriores de uma rubrica do "infoPerApur".

**Comment by tiagobentotst** [comment]
Boa tarde,
A implementação segue o manual do esocial, onde o campo infoPerApur possui apenas uma ocorrência

**Comment by fariasdouglas** [comment]
Bom dia,

Obrigado pelo retorno. Sobre o bloco "infoPerApur" estamos implementando de acordo com o manual do eSocial e está tudo certo.
A dúvida é sobre o layout do bloco "infoPerAnt", estamos com problemas para implementar o campo "remunOrgSuc" no EVENTo S-1202. Temos informações neste bloco com muitos meses "perRef". Você teria algum modelo para nos orientar na montagem deste bloco "infoPerAnt". Veja o erro que estamos enfrentando:

Evento 38876: Não foi possível gerar o XML - O XML é inválido em relação ao esquema - cvc-complex-type.2.4.b: The content of element 'infoPerAnt' is not complete. One of '{"http://www.esocial.gov.br/schema/evt/evtRmnRPPS/v_S_01_00_00":remunOrgSuc}' is expected.
