### ISSUE TITLE
Retificação S-1207

### ISSUE THREAD

**Issue by rafaeld3castro** [tst-labs/esocial#343]
Enviamos alguns eventos de para retificar alguns envios do S-1207 que foram com erro. As retificações foram recebidas no eSocial (gerou protocolo e recibo), porém ao enviar o evento de fechamento dos periódicos recebemos o seguinte erro:

**1692: O Benefício XXXXXXX do Beneficiário XXXXXXX consta na base de dados do Ambiente Nacional do eSocial, mas não foi informada sua remuneração. Ação sugerida: verificar se a falta de informação é decorrente de dificuldades operacionais ou se é possível efetuar a regularização.**

O evento de fechamento gerou recibo, porém ficou com o estado PROCESSADO COM ERRO e na resposta do processamento ficou "Sucesso com advertência"

Alguém já passou por situação parecida ou tem ideia do que possa ser?

Desde já agradeço pela atenção.

**Comment by tiagobentotst** [comment]
O que vale é "Sucesso com advertência". Esse estado não estava previsto inicialmente na aplicação e ainda não tivemos tempo para resolver.

**Comment by rafaeld3castro** [comment]
> O que vale é "Sucesso com advertência". Esse estado não estava previsto inicialmente na aplicação e ainda não tivemos tempo para resolver.

Perfeito. Consideraremos como enviado com sucesso nas próximas ocorrências.

Com relação à esse erro **1692**, tem ideia do que possa ter causado essa situação do eSocial não reconhecer a remuneração do Beneficio mesmo com a retificação do S-1207 tendo sido processada com sucesso? Tem algum prazo de tempo para a retificação ser de fato aplicada na base do eSocial ou algo do tipo?

**Comment by rafaeld3castro** [comment]
Reabrimos a folha e tentamos enviar o S-1207 e deu erro indicando que o evento já se encontrava no eSocial. 

Então me parece que é alguma inconsistência do próprio eSocial, pois quando fechamos a folha dá o alerta que o Benefício não está lá, porém quando tentamos enviar dá erro dizendo que já foi enviado.

Grato pela atenção.
