### ISSUE TITLE
Ingressar no Rocket Chat

### ISSUE THREAD

**Issue by winaudio** [tst-labs/esocial#36]
Boa tarde, gostaria de participar e saber mais do projeto, poderiam me adicionar no Rocket Chat.

**Comment by tiagobentotst** [comment]
Olá,
devido à alta demanda, decidimos suspender temporariamente a inclusão de usuários no Rocket Chat. Enquanto isso, pedimos que enviem dúvidas e sugestões sobre o projeto abrindo issues com a label "question". Muito obrigado pelo interesse.
