### ISSUE TITLE
Invalid CSRF token found no esocial-jt-service

### ISSUE THREAD

**Issue by ricardobstj** [tst-labs/esocial#371]
Após a inclusão a inclusão do spring-boot-starter-security no esocial-jt-service, está ocorrendo o erro `Invalid CSRF token found`

**Comment by ricardobstj** [comment]
A correção me parece que deve ser feita no arquivo [SecurityConfigDisable.java](https://github.com/tst-labs/esocial/blob/78ae1ead661946dd8b73f48231e65ac560467a69/src/esocial-jt-service/src/main/java/br/jus/tst/esocialjt/SecurityConfigDisable.java#L13) alterando para

```java
        httpSecurity
                .cors().and().csrf().disable()
                .authorizeRequests()
                .antMatchers("/")
                .permitAll();
```

**Comment by harleymoura** [comment]
Se possível verifiquem a opção para configuração de habilitar e desabilitar o token CSRF.

**Comment by rodolfocop** [comment]
> A correção me parece que deve ser feita no arquivo [SecurityConfigDisable.java](https://github.com/tst-labs/esocial/blob/78ae1ead661946dd8b73f48231e65ac560467a69/src/esocial-jt-service/src/main/java/br/jus/tst/esocialjt/SecurityConfigDisable.java#L13) alterando para
> 
> ```java
>         httpSecurity
>                 .cors().and().csrf().disable()
>                 .authorizeRequests()
>                 .antMatchers("/")
>                 .permitAll();
> ```

Está solução resolveu para mim, obrigado!
