### ISSUE TITLE
ERRO 403 após atualização para versão v0.0.13-SNAPSHOT

### ISSUE THREAD

**Issue by Kennedi1313** [tst-labs/esocial#373]
Após a atualização de versão, qualquer POST que tento fazer para a API me retorna um 403. Exemplo:

![image](https://user-images.githubusercontent.com/13836595/227064868-71f46d39-3e19-4e30-913d-d85b46e7d4d8.png)

Esse POST foi feito no próprio swagger da API, no endpoint de ocorrencias, na tentativa de enviar um S2200. Já verifiquei e está tudo ok com o certificado e senha, inclusive a conexão é estabelecida sem problemas, como mostra o print a seguir:

![image](https://user-images.githubusercontent.com/13836595/227065032-28982deb-8cd4-465d-8dfb-3f3a5941f12d.png)

Alguma luz para o que pode estar ocasionando esse erro?

**Comment by pedroheavy** [comment]
Estou passando pela mesma situação! Alguém conseguiu resolver?

**Comment by Kennedi1313** [comment]
Eu estava rodando um mvn clean install no src e buildando a imagem na mão, e somente após isso subindo a aplicação com o docker-compose up. Aparentemente isso não é permitido. Quando eu subi com o docker-compose up sem fazer essas operações antes, o projeto funcionou da forma correta.
