### ISSUE TITLE
Evento 1210 - Json de exemplo no layout S-1.2

### ISSUE THREAD

**Issue by rafaeld3castro** [tst-labs/esocial#394]
Prezados,

Seria possível disponibilizar um json de exemplo do evento 1210, contemplando os novos grupos como o `infoIRComplem` por exemplo. Conferi nos exemplos que estão disponíveis no projeto e o `pagamentos.json` parece não ter os campos novos do layout S-1.2.

Desde já agradeço pela atenção.

**Comment by pedroheavy** [comment]
Conseguiu?

**Comment by rafaeld3castro** [comment]
> Conseguiu?

Conseguimos sim. Atualizamos a versão e conseguimos enviar com leiaute novo (S-1.2).

Estávamos mais na dúvida com relação ao grupos relacionado aos dependentes que não são informados nos periódicos, mas deu tudo certo no envio.

Grato pela atenção.
