### ISSUE TITLE
Problema de Conexão com o eSocial no Ambiente de Produção

### ISSUE THREAD

**Issue by obcassel** [tst-labs/esocial#416]
Prezados,

Estamos enfrentando dificuldades para estabelecer a conexão com o **eSocial no ambiente de Produção**, apesar de o mesmo funcionar corretamente no ambiente de Produção Restrita.

**Passos Seguidos:**
- Seguímos todos os passos descritos na documentação oficial da ferramenta.
- O certificado digital utilizado está válido (A1).
- Não utilizamos proxy.
- A conexão foi testada com sucesso no ambiente de **Produção Restrita**.
- Problema Identificado:
Ao realizar a conexão com o eSocial no ambiente de Produção, o seguinte erro é apresentado:
`I/O error: Couldn't kickstart handshaking; nested exception is javax.net.ssl.SSLException: Couldn't kickstart handshaking. Is proxyServer configured? ` 

**Comportamento Observado:**
O serviço web esocial-jt-service inicia normalmente, mas continua apresentando o ambiente web como "Produção Restrita".
Ao verificar o Status do Sistema, o componente esocial-gov permanece em estado de carregamento, indicando que a conexão não foi bem-sucedida.

**Testes Realizados:**
- Executamos a ferramenta em outra máquina e também em uma rede diferente.
- Geramos um novo certificado A1 válido.
- Mesmo após essas tentativas, a conexão funciona adequadamente no ambiente de Produção Restrita, mas continua falhando ao ser inicializada no ambiente de Produção.

**Solicitação:**
Gostaríamos de auxílio para identificar a causa raiz do problema e, se possível, solucionar a falha na conexão com o ambiente de Produção.

Agradecemos desde já pelo suporte!

**Comment by mythrhe** [comment]
Estou tendo o mesmo problema, @obcassel. A instabilidade começou a ocorrer na sexta-feira por volta das 21h. No sábado ainda conseguimos enviar alguns lotes até às 14h mas agora, todas tentativas de conexão ao ambiente de produção recebem o mesmo erro reportado acima. 

`I/O error: Couldn't kickstart handshaking; nested exception is javax.net.ssl.SSLException: Couldn't kickstart handshaking. Is proxyServer configured?  `

**Comment by obcassel** [comment]
Apenas para deixar registrado, hoje (segunda-feira), voltamos a efetuar os testes e a conexão com a PRODUCAO conectou adequadamente. Aparentemente era algum problema no servidor.

**Comment by obcassel** [comment]
Apenas para deixar registrado, hoje (segunda-feira), voltamos a efetuar os testes e a conexão com a PRODUCAO conectou adequadamente. Aparentemente era algum problema no servidor.
