### ISSUE TITLE
Qual layout foi utilizado para o desenvolvimento da solução?

### ISSUE THREAD

**Issue by filnet1** [tst-labs/esocial#82]
Prezados,

Gostaria de saber qual o layout foi utilizado para o desenvolvimento da solução?
É o 2.4.02 ? 
Tem algum evento da NDE 02 ?

Obrigado.

**Comment by tiagobentotst** [comment]
A versão do layout utilizada hoje é a 2.4.02, que é a versão aceita pelo ambiente de Produção Restrita. Os novos eventos da NDE 02 ainda não foram implementados pois ainda não são aceitos.
