### ISSUE TITLE
Implementar a transmissão do evento 5001 (Informações das contribuições sociais por trabalhador)

### ISSUE THREAD

**Issue by tiagobentotst** [tst-labs/esocial#84]

**Comment by tiagobentotst** [comment]
Este evento não é enviado ao eSocial-Gov, e sim recebido no retorno do processamento de eventos periódicos

**Comment by jchacel** [comment]
O evento S5001 consta no XML da resposta ao envio de cada evento S-1202, S-2299 ou S-2399, sendo gerado pelo ambiente nacional do eSocial e, portanto, não é um evento a ser enviado para aquele sistema pelo eSocial-JT.
